import type { City } from "../types";

export const cities: City[] = [
  {
    slug: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    lat: 27.1767,
    lng: 78.0081,
    servedStoreSlugs: ["agra-shyam-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "xypro-lithium-ion"],
    localFuelPricePerLitre: 99,
    localElectricityRatePerKwh: 7,
    nearbyCitySlugs: ["mathura", "aligarh"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Agra's mix of tourist circuits, local commerce and family commutes makes our Shahganj-Bodla showroom a busy first stop for EV-curious riders. No licence required, low running cost, doorstep test rides.",
    customerCount: "320+",
    scootersSoldCount: "110+",
  },
  {
    slug: "aligarh",
    name: "Aligarh",
    state: "Uttar Pradesh",
    lat: 27.8974,
    lng: 78.0880,
    servedStoreSlugs: ["aligarh-naveen-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "4all-lead-acid"],
    localFuelPricePerLitre: 98,
    localElectricityRatePerKwh: 6.8,
    nearbyCitySlugs: ["mathura", "agra"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Aligarh's student-heavy commute pattern is a natural fit for low-speed electric. The Khair Bypass showroom offers same-day test rides and EMI approvals in fifteen minutes.",
    customerCount: "260+",
    scootersSoldCount: "90+",
  },
  {
    slug: "alwar",
    name: "Alwar",
    state: "Rajasthan",
    lat: 27.5530,
    lng: 76.6346,
    servedStoreSlugs: ["alwar-jyoti-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "4all-lithium-ion"],
    localFuelPricePerLitre: 108,
    localElectricityRatePerKwh: 7.2,
    nearbyCitySlugs: ["jaipur", "delhi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Alwar's growing residential clusters and short intra-city distances suit our 25 km/h licence-free range. Visit Jyoti Nagar for a free test ride and an honest TCO walk-through.",
    customerCount: "210+",
    scootersSoldCount: "70+",
  },
  {
    slug: "belagavi",
    name: "Belagavi",
    state: "Karnataka",
    lat: 15.8497,
    lng: 74.4977,
    servedStoreSlugs: ["belagavi-shivaji-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 105,
    localElectricityRatePerKwh: 7.4,
    nearbyCitySlugs: ["dharwad", "hubballi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Belagavi sits on the Pune-Bangalore corridor, and our Shivaji Nagar showroom serves both daily commuters and the steady inter-city delivery flow. No licence, no registration, all electric.",
    customerCount: "240+",
    scootersSoldCount: "80+",
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    servedStoreSlugs: ["bengaluru-kalyan-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 103,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["tumakuru", "mysuru", "mandya"],
    localFaqIds: ["bengaluru-rto", "bengaluru-charging"],
    testimonialIds: ["t-priya-bengaluru", "t-arvind-bengaluru"],
    introCopy:
      "Bengaluru's stop-and-go traffic was made for electric scooters: predictable distances, short trips, and enough charging time at home. Our Kalyan Nagar Mobility Center is staffed with trained technicians who'll walk you through every detail before you buy. No licence required for any scooter in our lineup.",
    customerCount: "3,200+",
    scootersSoldCount: "1,100+",
  },
  {
    slug: "davanagere",
    name: "Davanagere",
    state: "Karnataka",
    lat: 14.4644,
    lng: 75.9218,
    servedStoreSlugs: ["davanagere-vidyanagar"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "xypro-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 7.3,
    nearbyCitySlugs: ["hubballi", "dharwad"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Davanagere's student and small-business density makes our Taralabalu Layout showroom one of the fastest-growing in the network. Same-day test rides, fifteen-minute EMI approvals.",
    customerCount: "180+",
    scootersSoldCount: "60+",
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    servedStoreSlugs: [
      "delhi-budh-vihar",
      "delhi-dwarka",
      "delhi-jahangirpuri",
      "delhi-krishna-nagar",
      "delhi-nawada",
    ],
    bestsellerScooterVariantSlugs: ["4all-lithium-ion", "xypro-lithium-ion"],
    localFuelPricePerLitre: 97,
    localElectricityRatePerKwh: 8,
    nearbyCitySlugs: ["gurugram", "ghaziabad", "sonipat", "rohtak"],
    localFaqIds: [],
    testimonialIds: ["t-vikram-delhi"],
    introCopy:
      "Delhi's air-quality imperatives make the switch to electric a public-health choice, not just a financial one. With five Mobility Centers across Budh Vihar, Dwarka, Jahangirpuri, Krishna Nagar and Nawada, we bring service-first EV ownership to every quadrant of the capital.",
    customerCount: "1,800+",
    scootersSoldCount: "620+",
  },
  {
    slug: "dharwad",
    name: "Dharwad",
    state: "Karnataka",
    lat: 15.4589,
    lng: 75.0078,
    servedStoreSlugs: ["dharwad-line-bazar"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 7.3,
    nearbyCitySlugs: ["hubballi", "belagavi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Dharwad and Hubballi form Karnataka's second-largest urban cluster. Our Line Bazar showroom is the daily ride for students at Karnatak University and delivery partners along the Pune-Bangalore highway.",
    customerCount: "190+",
    scootersSoldCount: "60+",
  },
  {
    slug: "ghaziabad",
    name: "Ghaziabad",
    state: "Uttar Pradesh",
    lat: 28.6692,
    lng: 77.4538,
    servedStoreSlugs: ["ghaziabad-meerut-road", "ghaziabad-tigri-circle"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "4all-lithium-ion"],
    localFuelPricePerLitre: 98,
    localElectricityRatePerKwh: 7.8,
    nearbyCitySlugs: ["delhi", "meerut"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Ghaziabad's twin showrooms on Meerut Road and Tigri Circle serve NCR commuters who want a real store within walking distance. Component-level warranty, doorstep test rides, fast EMI.",
    customerCount: "420+",
    scootersSoldCount: "140+",
  },
  {
    slug: "gurugram",
    name: "Gurugram",
    state: "Haryana",
    lat: 28.4595,
    lng: 77.0266,
    servedStoreSlugs: ["gurugram-mata-road"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 97,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["delhi", "rohtak", "sonipat"],
    localFaqIds: [],
    testimonialIds: ["t-meera-gurugram"],
    introCopy:
      "Gurugram's corporate campuses and gated communities are perfect for the ElectricPe ownership model: predictable commutes, dedicated parking, and accessible charging. Our Mata Road Mobility Center offers doorstep test rides across all NCR sectors.",
    customerCount: "620+",
    scootersSoldCount: "210+",
  },
  {
    slug: "hassan",
    name: "Hassan",
    state: "Karnataka",
    lat: 13.0072,
    lng: 76.0962,
    servedStoreSlugs: ["hassan-bm-road"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "4all-lithium-ion"],
    localFuelPricePerLitre: 105,
    localElectricityRatePerKwh: 7.4,
    nearbyCitySlugs: ["mysuru", "mandya"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Hassan's regional commerce role and university routes suit the Xypro lineup. Visit our B M Road showroom for a no-pressure test ride and a written warranty summary you can take home.",
    customerCount: "170+",
    scootersSoldCount: "55+",
  },
  {
    slug: "hubballi",
    name: "Hubballi",
    state: "Karnataka",
    lat: 15.3647,
    lng: 75.1240,
    servedStoreSlugs: ["hubballi-vidya-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 7.3,
    nearbyCitySlugs: ["dharwad", "belagavi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Hubballi is the commercial half of the Hubballi-Dharwad cluster. Our Vidya Nagar showroom on the Pune-Bangalore Road runs extended weekend test-ride hours to fit working schedules.",
    customerCount: "210+",
    scootersSoldCount: "70+",
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    servedStoreSlugs: ["jaipur-sanganer"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "xypro-lithium-ion"],
    localFuelPricePerLitre: 108,
    localElectricityRatePerKwh: 7,
    nearbyCitySlugs: ["alwar"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Jaipur riders have been some of the earliest ElectricPe adopters in Rajasthan. The combination of low top-speed legal advantages, minimal running cost, and doorstep service has resonated here. Visit our Sanganer Mobility Center for a test ride.",
    customerCount: "450+",
    scootersSoldCount: "160+",
  },
  {
    slug: "mandya",
    name: "Mandya",
    state: "Karnataka",
    lat: 12.5246,
    lng: 76.8966,
    servedStoreSlugs: ["mandya-bannur-road"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "xypro-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 7.4,
    nearbyCitySlugs: ["mysuru", "bengaluru"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Mandya sits between Bengaluru and Mysuru, and our Bannur-Mandya Road showroom serves both town riders and the long-haul commuter belt. Honest pricing, honest range numbers.",
    customerCount: "140+",
    scootersSoldCount: "45+",
  },
  {
    slug: "mathura",
    name: "Mathura",
    state: "Uttar Pradesh",
    lat: 27.4924,
    lng: 77.6737,
    servedStoreSlugs: ["mathura-sonkh-road"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "xypro-lithium-ion"],
    localFuelPricePerLitre: 99,
    localElectricityRatePerKwh: 7,
    nearbyCitySlugs: ["agra", "aligarh"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Mathura's pilgrim-driven daily flows and tight residential lanes are exactly the conditions our scooters were built for. Goverdhan Chauraha is the door to our showroom and to a free test ride.",
    customerCount: "180+",
    scootersSoldCount: "60+",
  },
  {
    slug: "meerut",
    name: "Meerut",
    state: "Uttar Pradesh",
    lat: 28.9845,
    lng: 77.7064,
    servedStoreSlugs: ["meerut-garh-road", "meerut-roorkee-road"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 98,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["ghaziabad", "delhi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Meerut hosts two of our Mobility Centers (on Garh Road and Roorkee Road), covering both sides of the city. Same-day service, in-house technicians, written warranty.",
    customerCount: "380+",
    scootersSoldCount: "130+",
  },
  {
    slug: "mysuru",
    name: "Mysuru",
    state: "Karnataka",
    lat: 12.2958,
    lng: 76.6394,
    servedStoreSlugs: ["mysuru-kg-koppal"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 7.4,
    nearbyCitySlugs: ["mandya", "hassan", "bengaluru"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Mysuru's planned grid and cycle-friendly streets are an EV-natural environment. Our K G Koppal showroom near the Railway Gate offers extended weekend test-ride hours.",
    customerCount: "260+",
    scootersSoldCount: "85+",
  },
  {
    slug: "rohtak",
    name: "Rohtak",
    state: "Haryana",
    lat: 28.8955,
    lng: 76.6066,
    servedStoreSlugs: ["rohtak-chhotu-ram-nagar"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "4all-lithium-ion"],
    localFuelPricePerLitre: 97,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["sonipat", "gurugram", "delhi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Rohtak's university and government-services footprint drives steady demand for low-cost, low-maintenance EVs. Our Chhotu Ram Nagar showroom is on the Outer City Road, easy to reach from any side.",
    customerCount: "190+",
    scootersSoldCount: "60+",
  },
  {
    slug: "sonipat",
    name: "Sonipat",
    state: "Haryana",
    lat: 28.9931,
    lng: 77.0151,
    servedStoreSlugs: ["sonipat-sector-13"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "4all-lithium-ion"],
    localFuelPricePerLitre: 97,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["delhi", "rohtak"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Sonipat's mix of educational institutions and industrial clusters along the Delhi Road creates strong daily-commute demand. Our Sector-13 showroom serves both ends.",
    customerCount: "160+",
    scootersSoldCount: "55+",
  },
  {
    slug: "tumakuru",
    name: "Tumakuru",
    state: "Karnataka",
    lat: 13.3392,
    lng: 77.1140,
    servedStoreSlugs: ["tumakuru-main-road"],
    bestsellerScooterVariantSlugs: ["xypro-lead-acid", "xypro-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 7.4,
    nearbyCitySlugs: ["bengaluru", "mandya"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Tumakuru sits on the Bengaluru-Pune corridor and is rapidly becoming an industrial satellite of Bengaluru. Our Main Road showroom opposite SBI is the local hub for licence-free EVs.",
    customerCount: "150+",
    scootersSoldCount: "50+",
  },
];

export const getCity = (slug: string): City | undefined =>
  cities.find((c) => c.slug === slug);

export const allCitySlugs = cities.map((c) => c.slug);
