import type { BlogPostMeta } from "../types";

const COVER = "/img/home_hero_section_2.webp";

const authors = {
  akshara: {
    name: "Akshara",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  chitrarth: {
    name: "Chitrarth Tomar",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  electricpe: {
    name: "ElectricPe Team",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  harshith: {
    name: "Harshith",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  pratheek: {
    name: "Pratheek",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  riya: {
    name: "Riya",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  roshan: {
    name: "Roshan",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  sara: {
    name: "Sara Sethiya",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  shreya: {
    name: "Shreya",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
  shubham: {
    name: "Shubham",
    avatar: COVER,
    role: "ElectricPe Editorial",
  },
} as const;

export const blogPosts: BlogPostMeta[] = [
  {
    slug: "how-evs-are-redefining-vehicle-design",
    title: "How EVs Are Redefining Vehicle Design",
    dek: "Automobile design is evolving rapidly with the widespread adoption of electric vehicles. Iconic automakers like Cadillac and Hummer have embraced electric power to reclaim their share in a market they once dominated.",
    coverImage: "/images/blog/How-EVs-Are-Changing-Vehicle-Design.jpg",
    author: authors.pratheek,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-10-25",
    readMinutes: 3,
  },
  {
    slug: "beginners-guide-to-buying-an-ev",
    title: "Beginner’s Guide to Buying an EV",
    dek: "With the shift towards electric vehicles gaining momentum, it’s no wonder many are embracing the future of mobility. If you’re considering making the switch to electric but don’t know where to start, this is he ultimate beginner’s guide to buying an EV.",
    coverImage: "/images/blog/Dark-Motorcycle-Review-Youtube-Thumbnail.png",
    author: authors.pratheek,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-10-16",
    readMinutes: 3,
  },
  {
    slug: "5-reasons-you-should-switch-to-ev",
    title: "5 Reasons You Should Switch to EV",
    dek: "Electric vehicles are no longer just a trend – they are the future of urban mobility. As cities become more congested and pollution continues to rise, people are looking for greener and more efficient ways to get around.",
    coverImage: "/images/blog/5-Reasons-to-Switch-to-EV-1.jpg",
    author: authors.pratheek,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-10-07",
    readMinutes: 4,
  },
  {
    slug: "6-benefits-of-low-speed-electric-scooters",
    title: "6 Benefits of Low-Speed Electric Scooters",
    dek: "With the on-set of the EV revolution, electric scooters have taken over Indian roads. With Ather, Ola, TVS and other giants thriving in the EV industry, we’re seeing a slow but steady decline of ICE scooters.",
    coverImage: "/images/blog/Blue-Background-Vlog-YouTube-Thumbnail.png",
    author: authors.pratheek,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-09-30",
    readMinutes: 5,
  },
  {
    slug: "2024s-electric-two-wheeler-lineup-exciting-new-launches-and-innovations-await",
    title: "2024 Electric Two-Wheelers Unveiled!",
    dek: "Discover 2024's top electric two-wheelers; innovation meets design.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-05-02",
    readMinutes: 4,
  },
  {
    slug: "ola-electric-announces-price-cuts-on-s1x-scooters-starting-at-rs-69999",
    title: "Ola Electric Cuts Prices on S1X Scooter Variants",
    dek: "Ola Electric has reduced prices across its S1X scooter range, making the entry model more affordable at just Rs 69,999.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-04-19",
    readMinutes: 4,
  },
  {
    slug: "india-launches-rs-500-crore-electric-mobility-promotion-scheme-emps-2024",
    title: "India Launches Rs 500 Crore Electric Mobility Promotion Scheme EMPS 2024",
    dek: "Starting April 1st, dive into India's electric future with the launch of the Rs 500 crore scheme aimed at accelerating electric mobility nationwide.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["Blogs"],
    tags: ["article"],
    publishedAt: "2024-04-02",
    readMinutes: 5,
  },
  {
    slug: "discover-the-revolutionary-gogoro-jego-the-future-of-urban-mobility",
    title: "Jego Launch Sets Record",
    dek: "Unlock urban mobility redefined! Dive into the world of Gogoro Jego, the smart scooter designed for the electric era. Eco-friendly, stylish, and affordable – it's time to elevate your ride.",
    coverImage: "/images/blog/Screenshot-2024-03-29-160603.png",
    author: authors.akshara,
    categories: ["News"],
    tags: ["article"],
    publishedAt: "2024-03-29",
    readMinutes: 5,
  },
  {
    slug: "indian-celebrities-ev-cars",
    title: "Indian Celebrities with Electric Cars: 2024 Latest Updates",
    dek: "Explore the surge in electric vehicle (EV) adoption among Indian celebrities and its impact on the EV landscape. Stay updated with the latest trends in sustainable mobility.",
    coverImage: COVER,
    author: authors.sara,
    categories: ["Articles"],
    tags: ["article"],
    publishedAt: "2024-03-26",
    updatedAt: "2024-03-28",
    readMinutes: 2,
  },
  {
    slug: "government-subsidy-scheme-unveiled",
    title: "Government Unveils New Scheme to Subsidize Electric Two and Three Wheelers",
    dek: "Discover the latest initiative from the government to boost the sales of electric two and three wheelers with the Electric Mobility Promotion Scheme (EMPS), 2024.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["News"],
    tags: ["article"],
    publishedAt: "2024-03-21",
    updatedAt: "2024-03-28",
    readMinutes: 2,
  },
  {
    slug: "indias-best-selling-ev-brands-of-february-2024",
    title: "India’s Best-selling EV Brands of February 2024!",
    dek: "The electric two-wheeler sector has expanded significantly in recent years. Sales of electric two-wheelers hit all-time highs in February 2024, a sign of the increasing demand for these vehicles.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["Articles"],
    tags: ["article"],
    publishedAt: "2024-03-13",
    readMinutes: 1,
  },
  {
    slug: "sokudo-launches-two-electric-scooters-prices-start-from-rs-59889",
    title: "Sokudo introduces electric scooters check the prices",
    dek: "Sokudu Electric India, a manufacturer of electric two-wheelers, has introduced two new electric scooters that comply with the FAME-II regulations",
    coverImage: COVER,
    author: authors.riya,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-03-02",
    readMinutes: 1,
  },
  {
    slug: "explore-the-hyundai-nexo-showcased-at-the-bharat-mobility-expo",
    title: "Discover the Hyundai Nexo at the Bharat Mobility Expo!",
    dek: "Hyundai's Nexo hydrogen fuel cell vehicle has offered consumers the ultimate form of electric mobility. The Nexo not only represents Hyundai's passion for advanced green vehicle development...",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["news"],
    publishedAt: "2024-02-27",
    readMinutes: 4,
  },
  {
    slug: "tata-harrier-ev-a-brave-step-towards-the-future-of-sustainable-mobility",
    title: "Tata Harrier EV: A Brave Step Towards the Future of Sustainable Mobility!",
    dek: "The Tata Harrier EV is evidence of Tata Motors’ unique use of technology and design. Its striking green colour distinguishes it from other cars and denotes that it is environmentally friendly. The Harrier EV will be equipped with Level 2 ADAS.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Articles"],
    tags: ["news"],
    publishedAt: "2024-02-16",
    readMinutes: 3,
  },
  {
    slug: "price-cut-makes-indias-electric-car-more-affordable",
    title: "Price Cut Makes India’s Electric Car More Affordable!",
    dek: "Dive into the latest update from MG Motor as it announces a substantial price cut for its compact electric offering, the MG Comet EV, in the Indian market.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-02-10",
    readMinutes: 3,
  },
  {
    slug: "ampere-electric-scooter-india",
    title: "New EV by Ampere coming soon in India",
    dek: "Embark on an extraordinary 5,100-kilometer journey across India with Ampere's groundbreaking electric scooter, the \"\"Ampere Nxg.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-02-03",
    readMinutes: 3,
  },
  {
    slug: "ola-s-new-e-bike-service",
    title: "Ola's new E-Bike Service",
    dek: "Ola, a pioneering force in India’s transportation landscape, unveils its latest innovation: e-bike services now available in Delhi and Hyderabad.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-30",
    readMinutes: 3,
  },
  {
    slug: "hero-motorcorps-2-in-1-electric-vehicle",
    title: "2-in-1 Electric Vehicle by Hero",
    dek: "Hero MotoCorp unveils Surge S32: A batmobile-like two-in-one electric vehicle",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-29",
    readMinutes: 3,
  },
  {
    slug: "apple-own-new-electric-vehicle",
    title: "Apple's New Electric Vehicle",
    dek: "Project Titan, set to debut in 2028. Led by Kevin Lynch, Apple adjusts its vision for the car, opting for limited autonomy features similar to Tesla's Autopilot system.",
    coverImage: COVER,
    author: authors.akshara,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-24",
    readMinutes: 5,
  },
  {
    slug: "rizta-athers-new-family-oriented-scooter",
    title: "Ather's new Family Oriented Scooter 'Rizta'",
    dek: "The well-known Bangalore-based producer of electric vehicles, Ather Energy, is about to refocus its efforts with the introduction of the \"\"Ather Rizta\"\" electric scooter..",
    coverImage: COVER,
    author: authors.shubham,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-23",
    readMinutes: 5,
  },
  {
    slug: "evolving-ev-regulations-in-india",
    title: "Evolving landscape of EV regulations in India",
    dek: "The EV sector is also witnessing an increased number of technology-related collaborations.....",
    coverImage: COVER,
    author: authors.shubham,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-22",
    readMinutes: 5,
  },
  {
    slug: "battery-recycling-can-help-evs-to-be-truly-green",
    title: "Battery Recycling can help EVs to be truly green",
    dek: "EV batteries must be carefully managed post-usage to prevent environmental harm.",
    coverImage: COVER,
    author: authors.shubham,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-20",
    readMinutes: 5,
  },
  {
    slug: "6000-kms-of-ev-ready-highways-on-golden-quadrilateral",
    title: "\"6,000 kms of EV-ready highways on Golden Quadrilateral\"",
    dek: "Over the next seven years, 6,000 km of highways will be equipped with charging infrastructure",
    coverImage: COVER,
    author: authors.shubham,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-17",
    readMinutes: 5,
  },
  {
    slug: "unveiling-xiaomis-first-electric-vehicle",
    title: "Unveiling Xiaomi's First Electric Vehicle",
    dek: "The renowned Chinese smartphone company ‘Xiaomi’ unwrapped its very first electric vehicle during its EV technology launch event on Thursday in Beijing, China.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["News"],
    tags: ["news"],
    publishedAt: "2024-01-10",
    readMinutes: 1,
  },
  {
    slug: "ather-450-apex-electric-scooter-launched-price-range-and-features",
    title: "Ather 450 Apex Electric Scooter Launched",
    dek: "Ather 450 Apex comes with an ex-showroom starting price of ₹ 1,88,999 and several outstanding features, which we will discuss in the following section.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["blog"],
    publishedAt: "2024-01-10",
    readMinutes: 2,
  },
  {
    slug: "not-so-known-ev-maintenance-practices",
    title: "Not-so-known EV Maintenance Practices!",
    dek: "Don't Water-Wash your EV Instead Just Do a Wet Cloth Cleanup...",
    coverImage: COVER,
    author: authors.sara,
    categories: ["Blogs"],
    tags: ["blog"],
    publishedAt: "2024-01-09",
    readMinutes: 3,
  },
  {
    slug: "the-launch-of-our-brand-new-yelahanka-mobility-centre",
    title: "New Yelahanka Mobility Centre",
    dek: "Yelahanka Mobility Centre contains all the leading EV brands and is built with a vision to simplify the needs of consumers and provide them with an enjoyable EV experience.",
    coverImage: COVER,
    author: authors.sara,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-12-29",
    readMinutes: 2,
  },
  {
    slug: "huge-demand-for-evs-in-the-corporate-fleet-market",
    title: "Huge Demand for EVs in the Corporate Fleet Market!",
    dek: "The entire world is facing a dire need to mitigate climate change and cut carbon emissions, which is speeding up the transition to sustainable transportation options. ",
    coverImage: COVER,
    author: authors.sara,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-12-28",
    updatedAt: "2023-12-29",
    readMinutes: 4,
  },
  {
    slug: "gemopai-scooter-showroom-price-gemopai-astrid-lite-gemopai-ryder-electric-scooter-price-list-2023",
    title: "\"Gemopai Scooter Showroom Price: Gemopai Astrid Lite, Gemopai Ryder Electric Scooter Price List 2023!\"",
    dek: "The Ryder and Astrid Lite electric scooters are an exquisite set that emerge in the crowded urban areas where life rushes to the pulse of the clock.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["scooty"],
    publishedAt: "2023-12-22",
    readMinutes: 2,
  },
  {
    slug: "ola-s1-air-the-electric-revolution",
    title: "Ola S1 Air: The Electric Revolution",
    dek: "The S1 Air emerges as a game changer in the EV market, offering more than just a means of transportation. It is designed with high-tech design and elements that give it an extremely attractive look while contributing to a greener environment.",
    coverImage: COVER,
    author: authors.sara,
    categories: ["Blogs"],
    tags: ["store", "suggestion", "vehicle"],
    publishedAt: "2023-12-08",
    updatedAt: "2023-12-15",
    readMinutes: 8,
  },
  {
    slug: "hero-vida-v1-pro-top-speed-mileage-and-vida-v1-pro-price",
    title: "All About the Hero Vida V1 Pro Electric Scooter in India",
    dek: "The Vida V1 Pro boasts an impressive range of up to 143 km, making it ideal for daily commutes. The scooter accelerates quickly, providing a smooth and efficient ride through the city’s traffic-laden streets.",
    coverImage: COVER,
    author: authors.sara,
    categories: ["Blogs"],
    tags: ["2w", "change", "future", "report"],
    publishedAt: "2023-12-05",
    updatedAt: "2024-03-02",
    readMinutes: 7,
  },
  {
    slug: "the-top-5-affordable-electric-scooters-in-india",
    title: "The Top 5 Affordable Electric Scooters in India",
    dek: "Want to live a more sustainable lifestyle without going over budget? We have everything covered. In our hunt for sustainable options, we explored the Indian market to offer you the most ideal and affordable electric scooters.",
    coverImage: COVER,
    author: authors.chitrarth,
    categories: ["Blogs"],
    tags: ["cost"],
    publishedAt: "2023-12-01",
    updatedAt: "2023-12-15",
    readMinutes: 6,
  },
  {
    slug: "new-tata-nano-electric-alternative-arriving-full-charge-in-only-30-minutes",
    title: "New Tata Nano Electric Alternative Arriving. Full Charge in Only 30 Minutes",
    dek: "Electric Car Production Ramping Up As the demand for electric automobiles grows, companies are stepping up their game to produce better vehicles.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["fast-charge", "nano", "tata"],
    publishedAt: "2023-11-30",
    readMinutes: 2,
  },
  {
    slug: "the-rise-of-electric-two-wheelers-a-consumer-behaviour-shift",
    title: "The Rise of Electric Two-Wheelers: A Consumer Behaviour Shift",
    dek: "India has gained great success in the EV industry; however, the preferences and evolving desires of Indian consumers for electric vehicles (EVs) are changing rapidly.",
    coverImage: COVER,
    author: authors.harshith,
    categories: ["Blogs"],
    tags: ["2w", "change", "future", "report"],
    publishedAt: "2023-11-27",
    readMinutes: 5,
  },
  {
    slug: "iet-india-mobility-award-2023-electricpe-scoops-success",
    title: "IET India Mobility Award 2023: ElectricPe Scoops Success",
    dek: "Innovations are limitless, much like success. As we proudly received the IET India Mobility Award 2023, the series of our endless efforts, creative ideas, hard work, failures, and little yet joyous celebrations went away before us like thin air.",
    coverImage: COVER,
    author: authors.chitrarth,
    categories: ["Blogs"],
    tags: ["iet", "achievement", "award", "electric", "success"],
    publishedAt: "2023-11-21",
    readMinutes: 4,
  },
  {
    slug: "what-is-the-electric-vehicle-revolution",
    title: "What is The Electric Vehicle Revolution?",
    dek: "India is the third largest energy-consuming country and is taking significant measures to achieve a net-zero carbon goal by 2070. Sustainable development and practices are at the centre of this journey.",
    coverImage: COVER,
    author: authors.shreya,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-08-09",
    updatedAt: "2023-10-28",
    readMinutes: 3,
  },
  {
    slug: "5-things-to-know-before-buying-an-ev",
    title: "5 Things to Know Before Buying an EV",
    dek: "Electric vehicles (EVs) have rapidly evolved into a sustainable and environmentally friendly mode of transportation people are considering converting to EVs as technology advances and accessibility improves. However, several important factors to consider before purchasing an EV. Here are five things to think about before purchasing an EV",
    coverImage: COVER,
    author: authors.shreya,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-08-04",
    updatedAt: "2023-08-08",
    readMinutes: 4,
  },
  {
    slug: "accelerating-ev-adoption-alternatives-to-subsidy-reductions",
    title: "Alternatives to Subsidy Reductions",
    dek: "There has been a growing global concern in terms of the impact of fuel-based vehicles on the environment and public health. This concern has acted as a push to adopt Electric Vehicles (EVs) as a more eco-friendly and sustainable alternative. ",
    coverImage: COVER,
    author: authors.shreya,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-08-01",
    readMinutes: 4,
  },
  {
    slug: "regenerative-braking-in-evs-harnessing-energy-for-a-greener-drive",
    title: "Regenerative Braking in EVs",
    dek: "Innovation in electric vehicles (EVs) continually broadens the possibilities for environmentally friendly transportation. Regenerative braking is a significant feature that distinguishes EVs from conventional internal combustion engine vehicles. This innovative technology improves the driving economy and helps create a greener and more environmentally friendly community. The following piece will examine the idea of regenerative braking in EVs and its workings, advantages, and potential to modify our travel.",
    coverImage: COVER,
    author: authors.shreya,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-07-27",
    updatedAt: "2023-07-28",
    readMinutes: 3,
  },
  {
    slug: "5-common-myths-about-ev-charging",
    title: "Debunking 5 Common Myths About EV Charging",
    dek: "Despite their growing popularity, a few myths exist about how Electric Vehicles (EVs) are charged. Such disinformation can discourage potential EV buyers and spread false information about electric mobility. We’ll debunk five popular misconceptions regarding EV charging in this article so that you have the truth and can decide whether to adopt electric mobility.",
    coverImage: COVER,
    author: authors.shreya,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-07-26",
    updatedAt: "2023-07-27",
    readMinutes: 3,
  },
  {
    slug: "8631-2",
    title: "5 Essential Locations for EV Charging Stations",
    dek: "Unfortunately, EV charging stations are not available everywhere, and as the popularity of EVs continues to rise, there is an increase in the demand for charging stations as well. To encourage seamless travel and preferably a more sustainable environment, we will explore the five places EV charging stations should be and what can be done about it in this blog.",
    coverImage: COVER,
    author: authors.shreya,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-07-25",
    readMinutes: 2,
  },
  {
    slug: "accelerating-ev-adoption-the-role-of-rwas",
    title: "Accelerating EV Adoption: The Role of RWAs",
    dek: "As the world transitions towards a sustainable future, EVs have emerged as a promising solution for reducing carbon emissions. However, for widespread adoption of EVs to take place, robust charging infrastructure is crucial.",
    coverImage: COVER,
    author: authors.roshan,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-07-14",
    readMinutes: 5,
  },
  {
    slug: "ev-charging-etiquettes-10-tips-for-better-ev-charging-experience",
    title: "10 tips for a better EV charging experience",
    dek: "Remember- what goes around comes around and therefore, we’ve listed below 10 EV charging tips that will help you, help others charge better than ever.",
    coverImage: COVER,
    author: authors.roshan,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-06-24",
    updatedAt: "2023-06-28",
    readMinutes: 3,
  },
  {
    slug: "weekend-getaway-bengaluru-to-nandi-hills",
    title: "Weekend Getaway: Bengaluru to Nandi Hills",
    dek: "As more and more people are becoming environmentally conscious, electric vehicles (EVs) are gaining popularity. If you are in Bangalore and looking for a short trip on your EV, Nandi Hills is an excellent destination",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-06-23",
    readMinutes: 3,
  },
  {
    slug: "state-of-ev-charging-infra-in-india",
    title: "State of EV Charging Infra in India",
    dek: "Electric vehicles are the newest entrant to the world of Mobility. In an attempt to go green and protect\\nour beautiful planet, we see the lion’s share of attention being given to the field of electric vehicles and related tech globally, and in India.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-06-23",
    readMinutes: 5,
  },
  {
    slug: "accessories-ev-owners-would-love",
    title: "Accessories EV Owners Would LOVE!",
    dek: "Electric vehicles are not just a trend, but a revolution in the automotive industry. They offer a greener, more sustainable, and cost-efficient alternative to ICE (Internal combustion Engine) vehicles. As EVs become increasingly popular, so does the demand for accessories designed specifically for EV owners. ",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-06-23",
    readMinutes: 4,
  },
  {
    slug: "do-electric-vehicles-require-special-maintenance",
    title: "Do Electric Vehicles Require Special Maintenance?",
    dek: "I’m glad you asked this question! An electric motor requires much simpler maintenance than an internal combustion engine. With no friction between any moving parts or exchanges between liquids and gases, it needs neither lubricant nor exhaust.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-06-23",
    readMinutes: 1,
  },
  {
    slug: "big-hotel-chains-to-add-ev-chargers-on-popular-routes-to-drive-travel-demand",
    title: "Big Hotel Chains to Add EV Chargers on Popular Routes to Drive Travel Demand",
    dek: "The availability of EV charging stations at hotels has made journeys from one destination to another more convenient for electric vehicle owners. IHCL, for example, installed 224 EV charging stations in 92 of its locations last year.",
    coverImage: COVER,
    author: authors.electricpe,
    categories: ["Blogs"],
    tags: ["ev"],
    publishedAt: "2023-06-23",
    readMinutes: 1,
  },
];

export const getBlogPost = (slug: string): BlogPostMeta | undefined =>
  blogPosts.find((p) => p.slug === slug);

export const getRelatedPosts = (
  slug: string,
  limit = 3,
): BlogPostMeta[] => {
  const current = getBlogPost(slug);
  if (!current) return blogPosts.slice(0, limit);
  const scored = blogPosts
    .filter((p) => p.slug !== slug)
    .map((p) => ({
      post: p,
      score: p.categories.filter((c) => current.categories.includes(c)).length,
    }))
    .sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.post);
};
