import type { Scooter } from "../types";

export const scooters: Scooter[] = [
  {
    brand: "xypro",
    variantSlug: "lithium-ion",
    name: "Xypro Lithium Ion",
    tagline: "Long range for city commutes. Lithium efficiency, lighter weight",
    priceOnRoad: 58000,
    emiFrom: 1999,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 82,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 40,000 km · Motor & Controller 1y",
    },
    colors: [
      {
        name: "Cherry Red",
        hex: "#C62828",
        gallery: ["/img/xypro_brand_banner.webp"],
      },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "Charges in 4 hours on any regular 5A socket",
      "Digital speedometer with remaining-range estimate",
      "Anti-theft alarm + remote-lock key fob",
      "USB charging port + detachable lithium battery",
    ],
    useCases: ["commute", "student", "family"],
    licenseRequired: false,
    faqIds: ["xypro-range", "xypro-charging", "xypro-warranty"],
    testimonialIds: ["t-priya-bengaluru", "t-arvind-bengaluru"],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "meerut",
      "ghaziabad",
      "mysuru",
      "hubballi",
    ],
    seo: {
      title: "Xypro Lithium Ion | 80 km+ Range Electric Scooter | ElectricPe",
      description:
        "Xypro Lithium Ion electric scooter. 80 km+ range, 25 km/h top speed, 4h charge, component-level warranty. No licence required. EMI from ₹1,999/month. Book a free test ride.",
    },
  },
  {
    brand: "xypro",
    variantSlug: "lead-acid",
    name: "Xypro Lead Acid",
    tagline: "Best-value daily rider. Trusted chemistry, proven parts",
    priceOnRoad: 42000,
    emiFrom: 1499,
    specs: {
      rangeKm: 50,
      topSpeedKmh: 25,
      chargeTimeHours: 6,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 96,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/xypro_brand_banner.webp"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/xypro_brand_banner.webp"] },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "50 km+ real-world range on a single charge",
      "Charges in 6 hours on any regular 5A socket",
      "Lowest upfront price in the Xypro lineup",
      "Replaceable lead-acid battery, easy roadside swap",
      "Digital speedometer, anti-theft alarm",
      "Service & parts at any ElectricPe Mobility Center",
    ],
    useCases: ["commute", "student", "family"],
    licenseRequired: false,
    faqIds: ["xypro-range", "xypro-battery-life"],
    testimonialIds: ["t-rajesh-bengaluru"],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "agra",
      "aligarh",
      "alwar",
      "meerut",
      "mathura",
      "rohtak",
      "sonipat",
    ],
    seo: {
      title: "Xypro Lead Acid | Best-Value 50 km+ EV Scooter | ElectricPe",
      description:
        "Xypro Lead Acid electric scooter. 50 km+ range, 25 km/h top speed, 6h charge, component-level warranty. No licence required. EMI from ₹1,499/month. Book a free test ride.",
    },
  },
  {
    brand: "jett",
    variantSlug: "lithium-ion",
    name: "Jett Lithium Ion",
    tagline: "Elegant, spacious, built for the family. Daily rides with cargo comfort",
    priceOnRoad: 70000,
    emiFrom: 2499,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 88,
      payloadKg: 160,
      wheelSize: "12 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 40,000 km · Motor & Controller 1y",
    },
    colors: [
      { name: "Crimson", hex: "#B71C1C", gallery: ["/img/jett_brand_banner.webp"] },
    ],
    heroGallery: ["/img/jett_brand_banner.webp"],
    featureBullets: [
      "80 km+ range, enough for two daily commutes + errands",
      "Cushioned dual-seat with lumbar support",
      "Large under-seat storage (10 kg luggage capacity)",
      "12-inch wheels for smoother Indian roads",
      "Detachable lithium battery, charge at home or desk",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["jett-storage", "jett-comfort"],
    testimonialIds: ["t-shalini-delhi"],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "ghaziabad",
      "mysuru",
      "hubballi",
      "belagavi",
    ],
    seo: {
      title: "Jett Lithium Ion | 80 km+ Family Electric Scooter | ElectricPe",
      description:
        "Jett Lithium Ion electric scooter with 12-inch wheels, 10kg storage, 80 km+ range. Built for family rides. Component-level warranty. EMI from ₹2,499/month.",
    },
  },
  {
    brand: "jett",
    variantSlug: "lead-acid",
    name: "Jett Lead Acid",
    tagline: "Same elegance, lighter on the wallet. Proven battery chemistry",
    priceOnRoad: 55000,
    emiFrom: 1899,
    specs: {
      rangeKm: 50,
      topSpeedKmh: 25,
      chargeTimeHours: 6,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 102,
      payloadKg: 160,
      wheelSize: "12 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/jett_brand_banner.webp"] },
    ],
    heroGallery: ["/img/jett_brand_banner.webp"],
    featureBullets: [
      "50 km+ range for predictable daily use",
      "Charges in 6 hours on a regular 5A socket",
      "Same seat + storage + wheels as the lithium Jett",
      "Replaceable battery, easy to service anywhere",
      "Starting at ₹55,000 on-road",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["jett-comfort"],
    testimonialIds: [],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "meerut",
      "hubballi",
      "mysuru",
    ],
    seo: {
      title: "Jett Lead Acid | Best-Value Family EV Scooter | ElectricPe",
      description:
        "Jett Lead Acid electric scooter. 50 km+ range, 12-inch wheels, 10kg storage. 6h charge. Component-level warranty. EMI from ₹1,899/month.",
    },
  },
  {
    brand: "4all",
    variantSlug: "lithium-ion",
    name: "4ALL Lithium Ion",
    tagline: "Best range, zero hassle. No registration, no licence, no stress",
    priceOnRoad: 70000,
    emiFrom: 2499,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 85,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 40,000 km · Motor & Controller 1y",
    },
    colors: [
      { name: "Cloud White", hex: "#FAFAFA", gallery: ["/img/4all_brand_banner.webp"] },
    ],
    heroGallery: ["/img/4all_brand_banner.webp"],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "No licence, no registration. Ride it home the same day",
      "Detachable battery, charge indoors in 4 hours",
      "LED headlamp + digital console",
    ],
    useCases: ["commute", "family", "student"],
    licenseRequired: false,
    faqIds: ["4all-licence", "4all-range"],
    testimonialIds: [],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "ghaziabad",
      "mysuru",
      "alwar",
      "dharwad",
    ],
    seo: {
      title: "4ALL Lithium Ion | 80 km+ No-Licence EV Scooter | ElectricPe",
      description:
        "4ALL Lithium Ion electric scooter. 80 km+ range, no licence, no registration. Component-level warranty. EMI from ₹2,499/month. Book a free test ride.",
    },
  },
  {
    brand: "4all",
    variantSlug: "lead-acid",
    name: "4ALL Lead Acid",
    tagline: "Hassle-free ownership with classic lead-acid reliability",
    priceOnRoad: 56000,
    emiFrom: 1999,
    specs: {
      rangeKm: 50,
      topSpeedKmh: 25,
      chargeTimeHours: 6,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 98,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Cloud White", hex: "#FAFAFA", gallery: ["/img/4all_brand_banner.webp"] },
    ],
    heroGallery: ["/img/4all_brand_banner.webp"],
    featureBullets: [
      "50 km+ range, best in its price bracket",
      "Charges in 6 hours on any 5A socket",
      "No licence, no registration required",
      "Proven lead-acid chemistry, serviceable anywhere",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["4all-licence"],
    testimonialIds: [],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "meerut",
      "sonipat",
      "rohtak",
      "mathura",
    ],
    seo: {
      title: "4ALL Lead Acid | 50 km+ Best-Value EV Scooter | ElectricPe",
      description:
        "4ALL Lead Acid electric scooter. 50 km+ range, 6h charge, no licence required. Component-level warranty. EMI from ₹1,999/month.",
    },
  },
  {
    brand: "vibe",
    variantSlug: "lithium-ion",
    name: "Vibe Lithium Ion",
    tagline: "Modern-style daily ride. Lithium efficiency, light to handle",
    priceOnRoad: 70000,
    emiFrom: 2499,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 88,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 40,000 km · Motor & Controller 1y",
    },
    colors: [
      { name: "Cherry Red", hex: "#C62828", gallery: ["/img/cutouts/vibe_brand_banner-cutout.png"] },
      { name: "Ocean Blue", hex: "#1565C0", gallery: ["/img/products/cutouts/vibe-1.png"] },
      { name: "Cosmic Grey", hex: "#6B7280", gallery: ["/img/products/cutouts/vibe-3.png"] },
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/products/cutouts/vibe-2.png"] },
      { name: "Forest Green", hex: "#1B5E20", gallery: ["/img/products/cutouts/vibe-4.png"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/products/cutouts/vibe-5.png"] },
    ],
    heroGallery: [
      "/img/cutouts/vibe_brand_banner-cutout.png",
      "/img/products/cutouts/vibe-1.png",
      "/img/products/cutouts/vibe-3.png",
    ],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "Charges in 4 hours on any regular 5A socket",
      "Sleek modern silhouette with LED-style headlight",
      "Six colour options: red, blue, grey, white, green, black",
      "Detachable lithium battery, charge indoors",
    ],
    useCases: ["commute", "student"],
    licenseRequired: false,
    faqIds: ["charging-home"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram", "jaipur", "mysuru"],
    seo: {
      title: "Vibe Lithium Ion | 80 km+ Modern Electric Scooter | ElectricPe",
      description:
        "Vibe Lithium Ion electric scooter with modern styling. 80 km+ range, 25 km/h, 4h charge, six colour options. No licence required. EMI from ₹2,499/month.",
    },
  },
  {
    brand: "vibe",
    variantSlug: "lead-acid",
    name: "Vibe Lead Acid",
    tagline: "Same modern look, lighter on the wallet",
    priceOnRoad: 56000,
    emiFrom: 1999,
    specs: {
      rangeKm: 50,
      topSpeedKmh: 25,
      chargeTimeHours: 6,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 102,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Cherry Red", hex: "#C62828", gallery: ["/img/cutouts/vibe_brand_banner-cutout.png"] },
      { name: "Ocean Blue", hex: "#1565C0", gallery: ["/img/products/cutouts/vibe-1.png"] },
      { name: "Cosmic Grey", hex: "#6B7280", gallery: ["/img/products/cutouts/vibe-3.png"] },
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/products/cutouts/vibe-2.png"] },
      { name: "Forest Green", hex: "#1B5E20", gallery: ["/img/products/cutouts/vibe-4.png"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/products/cutouts/vibe-5.png"] },
    ],
    heroGallery: [
      "/img/cutouts/vibe_brand_banner-cutout.png",
      "/img/products/cutouts/vibe-2.png",
    ],
    featureBullets: [
      "50 km+ real-world range for predictable daily use",
      "Charges in 6 hours on any regular 5A socket",
      "Same modern Vibe silhouette as the lithium variant",
      "Six colour options to choose from",
      "Replaceable lead-acid battery, easy to service",
    ],
    useCases: ["commute", "student"],
    licenseRequired: false,
    faqIds: ["charging-home"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram", "jaipur"],
    seo: {
      title: "Vibe Lead Acid | 50 km+ Modern EV Scooter | ElectricPe",
      description:
        "Vibe Lead Acid electric scooter. 50 km+ range, 6h charge, six colour options. No licence required. Component-level warranty. EMI from ₹1,999/month.",
    },
  },
  {
    brand: "rapter",
    variantSlug: "lithium-ion",
    name: "Raptor 2.0 Lithium Ion",
    tagline: "Sporty urban presence with no-paperwork ride",
    priceOnRoad: 72000,
    emiFrom: 2599,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 95,
      payloadKg: 160,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 40,000 km · Motor & Controller 1y",
    },
    colors: [
      { name: "Ocean Blue", hex: "#1565C0", gallery: ["/img/cutouts/rapter_brand_banner-cutout.png"] },
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/products/cutouts/rapter-1.png"] },
      { name: "Forest Green", hex: "#1B5E20", gallery: ["/img/products/cutouts/rapter-3.png"] },
      { name: "Cherry Red", hex: "#C62828", gallery: ["/img/products/cutouts/rapter-2.png"] },
      { name: "Cosmic Grey", hex: "#6B7280", gallery: ["/img/products/cutouts/rapter-4.png"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/products/cutouts/rapter-5.png"] },
    ],
    heroGallery: [
      "/img/cutouts/rapter_brand_banner-cutout.png",
      "/img/products/cutouts/rapter-1.png",
      "/img/products/cutouts/rapter-3.png",
    ],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "Charges in 4 hours on any regular 5A socket",
      "Larger front fairing and bolder sport stance",
      "Six colour options: blue, white, green, red, grey, black",
      "Detachable lithium battery for indoor charging",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["charging-home"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram", "mysuru", "hubballi"],
    seo: {
      title: "Raptor 2.0 Lithium Ion | 80 km+ Sport-Style EV Scooter | ElectricPe",
      description:
        "Raptor 2.0 Lithium Ion electric scooter with bold sport stance. 80 km+ range, 25 km/h, 4h charge, six colour options. No licence required. EMI from ₹2,599/month.",
    },
  },
  {
    brand: "rapter",
    variantSlug: "lead-acid",
    name: "Raptor 2.0 Lead Acid",
    tagline: "Same sport stance, lighter on the wallet",
    priceOnRoad: 58000,
    emiFrom: 2099,
    specs: {
      rangeKm: 50,
      topSpeedKmh: 25,
      chargeTimeHours: 6,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 108,
      payloadKg: 160,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Ocean Blue", hex: "#1565C0", gallery: ["/img/cutouts/rapter_brand_banner-cutout.png"] },
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/products/cutouts/rapter-1.png"] },
      { name: "Forest Green", hex: "#1B5E20", gallery: ["/img/products/cutouts/rapter-3.png"] },
      { name: "Cherry Red", hex: "#C62828", gallery: ["/img/products/cutouts/rapter-2.png"] },
      { name: "Cosmic Grey", hex: "#6B7280", gallery: ["/img/products/cutouts/rapter-4.png"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/products/cutouts/rapter-5.png"] },
    ],
    heroGallery: [
      "/img/cutouts/rapter_brand_banner-cutout.png",
      "/img/products/cutouts/rapter-1.png",
    ],
    featureBullets: [
      "50 km+ real-world range for predictable daily use",
      "Charges in 6 hours on any regular 5A socket",
      "Same sport-stance body as the lithium Raptor 2.0",
      "Six colour options to choose from",
      "Replaceable lead-acid battery, easy to service",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["charging-home"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram"],
    seo: {
      title: "Raptor 2.0 Lead Acid | 50 km+ Sport-Style EV Scooter | ElectricPe",
      description:
        "Raptor 2.0 Lead Acid electric scooter with sport stance. 50 km+ range, 6h charge, six colour options. No licence required. Component-level warranty. EMI from ₹2,099/month.",
    },
  },
  {
    brand: "sniper-duo",
    variantSlug: "lithium-ion",
    name: "Sniper Duo Lithium Ion",
    tagline: "Two-up daily commute, lithium speed of charging",
    priceOnRoad: 58000,
    emiFrom: 2099,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 95,
      payloadKg: 160,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Lithium battery 3y · Motor, Controller & Charger 1y",
    },
    colors: [
      { name: "Cherry Red", hex: "#C62828", gallery: ["/img/products/cutouts/sniper-duo-1.png"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/products/cutouts/sniper-duo-2.png"] },
      { name: "Ocean Blue", hex: "#1565C0", gallery: ["/img/products/cutouts/sniper-duo-3.png"] },
      { name: "Cosmic Grey", hex: "#6B7280", gallery: ["/img/products/cutouts/sniper-duo-4.png"] },
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/products/cutouts/sniper-duo-5.png"] },
      { name: "Forest Green", hex: "#1B5E20", gallery: ["/img/products/cutouts/sniper-duo-6.png"] },
    ],
    heroGallery: [
      "/img/cutouts/sniper-duo_brand_banner-cutout.png",
      "/img/products/cutouts/sniper-duo-1.png",
      "/img/products/cutouts/sniper-duo-2.png",
    ],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "Charges in 4 hours on any regular 5A socket",
      "Wider dual seat tuned for two-up riding",
      "Six colour options: red, black, blue, grey, white, green",
      "3-year warranty on the lithium battery",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["charging-home"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram"],
    seo: {
      title: "Sniper Duo Lithium Ion | 80 km+ Two-Up EV Scooter | ElectricPe",
      description:
        "Sniper Duo Lithium Ion electric scooter built for two-up daily riding. 80 km+ range, 25 km/h, 4h charge, six colour options. No licence required. EMI from ₹2,099/month.",
    },
  },
  {
    brand: "sniper-duo",
    variantSlug: "lead-acid",
    name: "Sniper Duo Lead Acid",
    tagline: "Best-price two-up commute, proven battery chemistry",
    priceOnRoad: 44000,
    emiFrom: 1599,
    specs: {
      rangeKm: 50,
      topSpeedKmh: 25,
      chargeTimeHours: 6,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 108,
      payloadKg: 160,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery, Charger, Motor & Controller 1 year",
    },
    colors: [
      { name: "Cherry Red", hex: "#C62828", gallery: ["/img/products/cutouts/sniper-duo-1.png"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/products/cutouts/sniper-duo-2.png"] },
      { name: "Ocean Blue", hex: "#1565C0", gallery: ["/img/products/cutouts/sniper-duo-3.png"] },
      { name: "Cosmic Grey", hex: "#6B7280", gallery: ["/img/products/cutouts/sniper-duo-4.png"] },
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/products/cutouts/sniper-duo-5.png"] },
      { name: "Forest Green", hex: "#1B5E20", gallery: ["/img/products/cutouts/sniper-duo-6.png"] },
    ],
    heroGallery: [
      "/img/cutouts/sniper-duo_brand_banner-cutout.png",
      "/img/products/cutouts/sniper-duo-1.png",
    ],
    featureBullets: [
      "50 km+ real-world range for predictable daily use",
      "Charges in 6 hours on any regular 5A socket",
      "Same two-up body as the lithium Sniper Duo",
      "Six colour options to choose from",
      "Component-level 1-year warranty on battery, charger, motor and controller",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["charging-home"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram"],
    seo: {
      title: "Sniper Duo Lead Acid | 50 km+ Two-Up EV Scooter | ElectricPe",
      description:
        "Sniper Duo Lead Acid electric scooter built for two-up daily riding. 50 km+ range, 25 km/h, 6h charge, six colour options. No licence required. EMI from ₹1,599/month.",
    },
  },
];

export const scootersByBrand = scooters.reduce<Record<string, Scooter[]>>(
  (acc, s) => {
    (acc[s.brand] ??= []).push(s);
    return acc;
  },
  {},
);

export const getScooter = (
  brand: string,
  variantSlug: string,
): Scooter | undefined =>
  scooters.find((s) => s.brand === brand && s.variantSlug === variantSlug);

export const getBrandFlagship = (brand: string): Scooter | undefined =>
  scooters.find((s) => s.brand === brand && s.variantSlug === "lithium-ion") ??
  scooters.find((s) => s.brand === brand);
