import type { Scooter } from "../types";

export const scooters: Scooter[] = [
  {
    brand: "xypro",
    variantSlug: "lithium-ion",
    name: "Xypro Lithium Ion",
    tagline: "Long range for city commutes. Lithium efficiency, lead-acid pricing",
    priceOnRoad: 36000,
    emiFrom: 1299,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 82,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 10,000 km · Motor & Controller 1y",
    },
    colors: [
      {
        name: "Cherry Red",
        hex: "#C62828",
        gallery: ["/img/xypro_brand_banner.webp"],
      },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "Charges in 4 hours on any regular 5A socket",
      "Digital speedometer with remaining-range estimate",
      "Anti-theft alarm + remote-lock key fob",
      "USB charging port + detachable lithium battery",
    ],
    useCases: ["commute", "student", "family"],
    licenseRequired: false,
    faqIds: ["xypro-range", "xypro-charging", "xypro-warranty"],
    testimonialIds: ["t-priya-bengaluru", "t-arvind-bengaluru"],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "meerut",
      "ghaziabad",
      "mysuru",
      "hubballi",
    ],
    seo: {
      title: "Xypro Lithium Ion | 80 km+ Range Electric Scooter | ElectricPe",
      description:
        "Xypro Lithium Ion electric scooter. 80 km+ range, 25 km/h top speed, 4h charge, component-level warranty. No licence required. EMI from ₹1,299/month. Book a free test ride.",
    },
  },
  {
    brand: "xypro",
    variantSlug: "lead-acid",
    name: "Xypro Lead Acid",
    tagline: "Budget-friendly daily rider. Trusted chemistry, proven parts",
    priceOnRoad: 36000,
    emiFrom: 1299,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 96,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/xypro_brand_banner.webp"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/xypro_brand_banner.webp"] },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "Lowest upfront price in the ElectricPe range",
      "Replaceable lead-acid battery, easy roadside swap",
      "Digital speedometer, anti-theft alarm",
      "Service & parts at any ElectricPe Mobility Center",
    ],
    useCases: ["commute", "student", "family"],
    licenseRequired: false,
    faqIds: ["xypro-range", "xypro-battery-life"],
    testimonialIds: ["t-rajesh-bengaluru"],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "agra",
      "aligarh",
      "alwar",
      "meerut",
      "mathura",
      "rohtak",
      "sonipat",
    ],
    seo: {
      title: "Xypro Lead Acid | Best-Value 80 km+ EV Scooter | ElectricPe",
      description:
        "Xypro Lead Acid electric scooter. 80 km+ range, 25 km/h top speed, component-level warranty. No licence required. EMI from ₹1,299/month. Book a free test ride.",
    },
  },
  {
    brand: "jett",
    variantSlug: "lithium-ion",
    name: "Jett Lithium Ion",
    tagline: "Elegant, spacious, built for the family. Daily rides with cargo comfort",
    priceOnRoad: 54000,
    emiFrom: 1899,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 88,
      payloadKg: 160,
      wheelSize: "12 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 10,000 km · Motor & Controller 1y",
    },
    colors: [
      { name: "Crimson", hex: "#B71C1C", gallery: ["/img/jett_brand_banner.webp"] },
    ],
    heroGallery: ["/img/jett_brand_banner.webp"],
    featureBullets: [
      "80 km+ range, enough for two daily commutes + errands",
      "Cushioned dual-seat with lumbar support",
      "Large under-seat storage (10 kg luggage capacity)",
      "12-inch wheels for smoother Indian roads",
      "Detachable lithium battery, charge at home or desk",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["jett-storage", "jett-comfort"],
    testimonialIds: ["t-shalini-delhi"],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "ghaziabad",
      "mysuru",
      "hubballi",
      "belagavi",
    ],
    seo: {
      title: "Jett Lithium Ion | 80 km+ Family Electric Scooter | ElectricPe",
      description:
        "Jett Lithium Ion electric scooter with 12-inch wheels, 10kg storage, 80 km+ range. Built for family rides. Component-level warranty. EMI from ₹1,899/month.",
    },
  },
  {
    brand: "jett",
    variantSlug: "lead-acid",
    name: "Jett Lead Acid",
    tagline: "Same elegance, lighter on the wallet. Proven battery chemistry",
    priceOnRoad: 54000,
    emiFrom: 1899,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 102,
      payloadKg: 160,
      wheelSize: "12 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/jett_brand_banner.webp"] },
    ],
    heroGallery: ["/img/jett_brand_banner.webp"],
    featureBullets: [
      "80 km+ range for predictable daily use",
      "Same seat + storage + wheels as the lithium Jett",
      "Replaceable battery, easy to service anywhere",
      "Starting at ₹54,000 on-road",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["jett-comfort"],
    testimonialIds: [],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "meerut",
      "hubballi",
      "mysuru",
    ],
    seo: {
      title: "Jett Lead Acid | Best-Value Family EV Scooter | ElectricPe",
      description:
        "Jett Lead Acid electric scooter. 80 km+ range, 12-inch wheels, 10kg storage. Component-level warranty. EMI from ₹1,899/month.",
    },
  },
  {
    brand: "4all",
    variantSlug: "lithium-ion",
    name: "4ALL Lithium Ion",
    tagline: "Best range, zero hassle. No registration, no licence, no stress",
    priceOnRoad: 56000,
    emiFrom: 1999,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 85,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 3y / 10,000 km · Motor & Controller 1y",
    },
    colors: [
      { name: "Cloud White", hex: "#FAFAFA", gallery: ["/img/4all_brand_banner.webp"] },
    ],
    heroGallery: ["/img/4all_brand_banner.webp"],
    featureBullets: [
      "80 km+ real-world range on a single charge",
      "No licence, no registration. Ride it home the same day",
      "Detachable battery, charge indoors in 4 hours",
      "LED headlamp + digital console",
    ],
    useCases: ["commute", "family", "student"],
    licenseRequired: false,
    faqIds: ["4all-licence", "4all-range"],
    testimonialIds: [],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "ghaziabad",
      "mysuru",
      "alwar",
      "dharwad",
    ],
    seo: {
      title: "4ALL Lithium Ion | 80 km+ No-Licence EV Scooter | ElectricPe",
      description:
        "4ALL Lithium Ion electric scooter. 80 km+ range, no licence, no registration. Component-level warranty. EMI from ₹1,999/month. Book a free test ride.",
    },
  },
  {
    brand: "4all",
    variantSlug: "lead-acid",
    name: "4ALL Lead Acid",
    tagline: "Hassle-free ownership with classic lead-acid reliability",
    priceOnRoad: 56000,
    emiFrom: 1999,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 98,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Battery 12 months · Motor & Controller 1y",
    },
    colors: [
      { name: "Cloud White", hex: "#FAFAFA", gallery: ["/img/4all_brand_banner.webp"] },
    ],
    heroGallery: ["/img/4all_brand_banner.webp"],
    featureBullets: [
      "80 km+ range, best range in its price bracket",
      "No licence, no registration required",
      "Proven lead-acid chemistry, serviceable anywhere",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["4all-licence"],
    testimonialIds: [],
    availabilityCities: [
      "bengaluru",
      "delhi",
      "gurugram",
      "jaipur",
      "meerut",
      "sonipat",
      "rohtak",
      "mathura",
    ],
    seo: {
      title: "4ALL Lead Acid | 80 km+ Best-Value EV Scooter | ElectricPe",
      description:
        "4ALL Lead Acid electric scooter. 80 km+ range, no licence required. Component-level warranty. EMI from ₹1,999/month.",
    },
  },
  {
    brand: "xypro",
    variantSlug: "swap",
    name: "Xypro Swap",
    tagline: "Own the scooter, subscribe the battery. Lowest upfront cost",
    priceOnRoad: 36000,
    emiFrom: 1299,
    specs: {
      rangeKm: 80,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.6,
      motorWattage: 250,
      weightKg: 75,
      payloadKg: 140,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "Road-legal (low-speed EV)",
      warranty: "Vehicle 1y · Battery via subscription",
    },
    colors: [
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/xypro_brand_banner.webp"] },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "Lowest sticker price: ₹36,000 on-road",
      "Battery-as-a-service: swap at any partner station in seconds",
      "Ideal for delivery riders who can't afford charging downtime",
      "No charging at home, no electricity bill spike",
    ],
    useCases: ["delivery"],
    licenseRequired: false,
    faqIds: ["xypro-swap-subscription"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "delhi", "gurugram"],
    seo: {
      title: "Xypro Swap | Battery Swap EV Scooter ₹36,000 | ElectricPe",
      description:
        "Xypro Swap electric scooter with battery-as-a-service. Lowest upfront cost at ₹36,000. Perfect for delivery partners. No charging downtime.",
    },
  },
];

export const scootersByBrand = scooters.reduce<Record<string, Scooter[]>>(
  (acc, s) => {
    (acc[s.brand] ??= []).push(s);
    return acc;
  },
  {},
);

export const getScooter = (
  brand: string,
  variantSlug: string,
): Scooter | undefined =>
  scooters.find((s) => s.brand === brand && s.variantSlug === variantSlug);

export const getBrandFlagship = (brand: string): Scooter | undefined =>
  scooters.find((s) => s.brand === brand && s.variantSlug === "lithium-ion") ??
  scooters.find((s) => s.brand === brand);
