/**
 * EV Charging-station landing pages — programmatic SEO content model.
 *
 * Distinct from `content/cities` (which is scooter-retail / store centric).
 * The ElectricPe charging app aggregates 25,000+ public chargers across India,
 * so these pages cover a pan-India footprint — including metros where there is
 * no physical Mobility Center.
 *
 * Source of truth: the client's SEO blueprint (Electricpe.pdf). H1 strings and
 * priorities are taken verbatim from that document; intro copy is original,
 * derived from the per-page rationale plus real geographic / market context.
 * No city-specific charger counts or addresses are invented here — only real
 * brand-level stats (see content/globals.ts) are surfaced in the template.
 */

export type ChargingPageType =
  | "city-hub"
  | "vehicle-city"
  | "highway"
  | "use-case";

export type ChargingPriority = "critical" | "high" | "medium";

export type ChargingPage = {
  /** Flat URL slug, e.g. "ev-charging-stations-bengaluru" (no leading slash). */
  slug: string;
  pageType: ChargingPageType;
  /** Display label for the location/topic, e.g. "Bengaluru". */
  name: string;
  /** State / region — city-hub & vehicle-city pages. */
  state?: string;
  tier?: "T1" | "T2" | "T3";
  /** EV-penetration note, verbatim from the blueprint. */
  evPenetration?: string;
  /** Operational status, verbatim from the blueprint. */
  operational?: string;
  /** Exact H1 / target keyword from the blueprint. */
  h1: string;
  /** <=60 char meta title (absolute — bypasses the global template). */
  metaTitle: string;
  /** Unique <=155 char meta description. */
  metaDescription: string;
  priority: ChargingPriority;
  /** Internal rationale from the blueprint (not rendered; seeds the intro). */
  rationale: string;
  /** Unique 2–3 sentence SEO body copy rendered under the H1. */
  intro: string;
  /** Other ChargingPage slugs for the internal-link block. */
  nearbyCitySlugs?: string[];
  /** Slug of a real scooter-retail city (links to /stores/{slug}) if one exists. */
  storeCitySlug?: string;
  /** vehicle-city pages only. */
  vehicle?: { brand: string; model: string };
  /** highway pages only. */
  route?: { from: string; to: string; distanceKm?: number };
  /** Extra charging FAQ ids to render (in addition to the category default). */
  faqIds?: string[];
};

/** Partner charging networks aggregated in the app (shared with the hub page). */
export const CHARGING_NETWORKS: string[] = [
  "Tata Power",
  "Adani EV",
  "BPCL",
  "Shell Recharge",
  "Jio-bp",
  "HP Charge",
  "Indian Oil",
  "Statiq",
  "ChargeZone",
  "Relux",
  "Magenta",
  "Ezili",
  "Fortum",
  "Numocity",
  "ChargeGrid",
  "Plugzmart",
  "Exicom",
  "Zeon",
  "Enviro",
  "BOLT",
  "Park+",
  "Volttic",
  "Exponent",
  "Kazam",
];

/** In-app filter facets surfaced on every charging page. */
export const CHARGING_FILTERS: string[] = [
  "Connector type (Type-2, CCS2, Bharat AC-001)",
  "Power output (3.3 kW → 150 kW)",
  "Network / operator",
  "Free vs paid",
  "24×7 availability",
];

export const chargingPages: ChargingPage[] = [
  {
    slug: "ev-charging-stations-bengaluru",
    pageType: "city-hub",
    name: "Bengaluru",
    state: "Karnataka",
    tier: "T1",
    evPenetration: "Yes — HQ",
    operational: "Yes — HQ",
    h1: "EV Charging Stations in Bengaluru — Find & Pay Instantly",
    metaTitle: "EV Charging Stations in Bengaluru | ElectricPe",
    metaDescription:
      "Find EV charging stations across Bengaluru in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "critical",
    rationale:
      "HQ city. 25,000+ chargers. India's highest 2W EV penetration. Core revenue market.",
    intro:
      "Bengaluru has India's densest two-wheeler EV base — and ElectricPe maps charging stations from every major network onto one screen. Open the app to see live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. No more juggling a dozen operator apps across the city.",
    nearbyCitySlugs: [
      "ev-charging-stations-mysuru",
      "ev-charging-stations-tumakuru",
      "ev-charging-stations-hubballi",
      "ev-charging-stations-mangaluru",
    ],
    storeCitySlug: "bengaluru",
  },
  {
    slug: "ev-charging-stations-delhi",
    pageType: "city-hub", name: "Delhi", state: "Delhi / NCR", tier: "T1",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Delhi — ElectricPe App",
    metaTitle: "Delhi EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Delhi in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "critical",
    rationale: "India's highest absolute EV adoption. Multiple mobility centres confirmed across the city.",
    intro: "Delhi has India's largest EV population on the road — and ElectricPe brings every major charging network onto one screen. Open the app to see live availability, filter by connector and speed, navigate turn-by-turn across the capital, and pay from a single wallet. No more switching between a dozen operator apps to top up.",
    nearbyCitySlugs: ["ev-charging-stations-gurugram","ev-charging-stations-noida","ev-charging-stations-ghaziabad","ev-charging-stations-faridabad"],
    storeCitySlug: "delhi",
  },
  {
    slug: "ev-charging-stations-mumbai",
    pageType: "city-hub", name: "Mumbai", state: "Maharashtra", tier: "T1",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Mumbai — ElectricPe",
    metaTitle: "Mumbai EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV anywhere in Mumbai with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and a single unified wallet.",
    priority: "critical",
    rationale: "Maharashtra is the #1 state for EV sales volume. Dense metro, strong 4W + 2W EV adoption.",
    intro: "Mumbai leads the country's top EV state for sales, with strong adoption across both cars and scooters. ElectricPe maps charging stations from every major network onto one screen, so you can check live availability, navigate turn-by-turn through the metro, and pay from a single wallet. Skip the hassle of juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-pune","ev-charging-stations-nashik","ev-charging-stations-nagpur"],
  },
  {
    slug: "ev-charging-stations-hyderabad",
    pageType: "city-hub", name: "Hyderabad", state: "Telangana", tier: "T1",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Hyderabad — Find Chargers",
    metaTitle: "Hyderabad EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Hyderabad in the ElectricPe app — live availability from 60+ networks, easy navigation and one unified wallet.",
    priority: "critical",
    rationale: "Telangana EV policy offers aggressive subsidies. IT sector means high-income 2W EV buyers.",
    intro: "Telangana's bold EV subsidies and Hyderabad's high-income IT workforce are driving fast-growing electric scooter ownership. ElectricPe pulls charging stations from every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app for the whole city.",
    nearbyCitySlugs: ["ev-charging-stations-visakhapatnam","ev-charging-stations-vijayawada","ev-charging-stations-bengaluru"],
  },
  {
    slug: "ev-charging-stations-pune",
    pageType: "city-hub", name: "Pune", state: "Maharashtra", tier: "T1",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Pune — Charge Your EV",
    metaTitle: "Pune EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Pune with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet to pay.",
    priority: "critical",
    rationale: "Strong 2W EV adoption. Automotive + IT belt creates a fleet opportunity.",
    intro: "Pune's automotive and IT belt has made it a hotspot for electric two-wheelers and growing fleet demand. ElectricPe maps charging stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet. No more switching between operator apps to keep moving.",
    nearbyCitySlugs: ["ev-charging-stations-mumbai","ev-charging-stations-nashik","ev-charging-stations-nagpur"],
  },
  {
    slug: "ev-charging-stations-chennai",
    pageType: "city-hub", name: "Chennai", state: "Tamil Nadu", tier: "T1",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Chennai — ElectricPe",
    metaTitle: "Chennai EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Chennai in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "critical",
    rationale: "Strong South India EV corridor. High TVS iQube and Ather 450X owner base.",
    intro: "As an anchor of the South India EV corridor, Chennai has a large base of TVS iQube and Ather riders looking for reliable charging. ElectricPe brings every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app instead of many.",
    nearbyCitySlugs: ["ev-charging-stations-coimbatore","ev-charging-stations-bengaluru","ev-charging-stations-tirupati"],
  },
  {
    slug: "ev-charging-stations-ahmedabad",
    pageType: "city-hub", name: "Ahmedabad", state: "Gujarat", tier: "T1",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Ahmedabad — Fast & Reliable",
    metaTitle: "Ahmedabad EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Ahmedabad with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "critical",
    rationale: "Gujarat has India's most aggressive EV policy. High e-3W and 2W EV penetration. Business hub.",
    intro: "Backed by Gujarat's industry-leading EV policy, Ahmedabad has strong uptake of electric three-wheelers and scooters across its busy business districts. ElectricPe maps charging stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet — no juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-surat","ev-charging-stations-vadodara"],
  },
  {
    slug: "ev-charging-stations-gurugram",
    pageType: "city-hub", name: "Gurugram", state: "Haryana", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Gurugram — Find EV Chargers",
    metaTitle: "Gurugram EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Gurugram in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "NCR tech corridor. Corporate EV fleet adoption. Confirmed mobility-centre presence.",
    intro: "Gurugram's NCR tech corridor is driving corporate EV fleets and a fast-rising base of daily commuters who need dependable charging. ElectricPe brings every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app for the whole corridor.",
    nearbyCitySlugs: ["ev-charging-stations-delhi","ev-charging-stations-faridabad","ev-charging-stations-noida","ev-charging-stations-jaipur"],
    storeCitySlug: "gurugram",
  },
  {
    slug: "ev-charging-stations-surat",
    pageType: "city-hub", name: "Surat", state: "Gujarat", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Surat — Find Chargers",
    metaTitle: "Surat EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Surat with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet to pay.",
    priority: "high",
    rationale: "Gujarat's 2nd-largest city. Diamond + textile industry means high per-capita income and a strong EV buyer base.",
    intro: "Surat's diamond and textile wealth has built a strong base of EV buyers across Gujarat's second-largest city. ElectricPe maps charging stations from every major network onto one screen, so you can check live availability, navigate turn-by-turn, and pay from a single wallet. Skip the hassle of juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-vadodara","ev-charging-stations-ahmedabad"],
  },
  {
    slug: "ev-charging-stations-vadodara",
    pageType: "city-hub", name: "Vadodara", state: "Gujarat", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Vadodara — ElectricPe",
    metaTitle: "Vadodara EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Vadodara in the ElectricPe app — live availability from 60+ networks, easy navigation and one unified wallet.",
    priority: "high",
    rationale: "Gujarat expansion. Industrial city with growing EV adoption.",
    intro: "As an industrial hub in Gujarat's expanding EV market, Vadodara is seeing steady growth in electric vehicle adoption. ElectricPe brings every major charging network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app instead of many.",
    nearbyCitySlugs: ["ev-charging-stations-ahmedabad","ev-charging-stations-surat"],
  },
  {
    slug: "ev-charging-stations-nagpur",
    pageType: "city-hub", name: "Nagpur", state: "Maharashtra", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Nagpur — ElectricPe",
    metaTitle: "Nagpur EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Nagpur with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet to pay.",
    priority: "medium",
    rationale: "Central India logistics hub. Government EV bus fleet. Maharashtra Tier-2 expansion.",
    intro: "As Central India's logistics hub with government EV bus fleets on the road, Nagpur is a key part of Maharashtra's Tier-2 EV expansion. ElectricPe maps charging stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet — no juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-pune","ev-charging-stations-mumbai","ev-charging-stations-nashik"],
  },
  {
    slug: "ev-charging-stations-noida",
    pageType: "city-hub", name: "Noida", state: "Uttar Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Noida — ElectricPe",
    metaTitle: "Noida EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Noida in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "NCR expansion. High-density IT parks and residential complexes drive EV demand.",
    intro: "Noida's dense IT parks and high-rise residential complexes are fuelling fast-growing EV demand across the NCR. ElectricPe brings every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app for the whole city.",
    nearbyCitySlugs: ["ev-charging-stations-delhi","ev-charging-stations-ghaziabad","ev-charging-stations-gurugram","ev-charging-stations-meerut"],
  },
  {
    slug: "ev-charging-stations-ghaziabad",
    pageType: "city-hub", name: "Ghaziabad", state: "Uttar Pradesh", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Ghaziabad",
    metaTitle: "Ghaziabad EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Ghaziabad with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Confirmed operational mobility centre on the Namo Bharat metro corridor. Already in the real footprint.",
    intro: "Sitting on the Namo Bharat metro corridor, Ghaziabad is a fast-growing EV market with charging already on the ground. ElectricPe maps stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet. Skip the hassle of juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-delhi","ev-charging-stations-noida","ev-charging-stations-meerut","ev-charging-stations-gurugram"],
    storeCitySlug: "ghaziabad",
  },
  {
    slug: "ev-charging-stations-faridabad",
    pageType: "city-hub", name: "Faridabad", state: "Haryana", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Faridabad — ElectricPe",
    metaTitle: "Faridabad EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Faridabad in the ElectricPe app — live availability from 60+ networks, easy navigation and one unified wallet.",
    priority: "high",
    rationale: "Industrial belt with a fleet-EV opportunity. Confirmed mobility-centre presence.",
    intro: "Faridabad's industrial belt is opening up a strong fleet-EV opportunity alongside everyday commuters. ElectricPe brings every major charging network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app instead of many.",
    nearbyCitySlugs: ["ev-charging-stations-delhi","ev-charging-stations-gurugram","ev-charging-stations-noida"],
  },
  {
    slug: "ev-charging-stations-chandigarh",
    pageType: "city-hub", name: "Chandigarh", state: "Punjab / Haryana", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Chandigarh — Find & Charge",
    metaTitle: "Chandigarh EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Chandigarh with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Affluent buyer base. Union Territory means centralised EV policy. Growing Ather + Ola adoption.",
    intro: "Chandigarh's affluent buyers and centralised Union Territory EV policy are driving rising Ather and Ola adoption across the city. ElectricPe maps charging stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet — no juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-delhi","ev-charging-stations-gurugram"],
  },
  {
    slug: "ev-charging-stations-lucknow",
    pageType: "city-hub", name: "Lucknow", state: "Uttar Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Lucknow — ElectricPe App",
    metaTitle: "Lucknow EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Lucknow in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Largest city in UP. PM E-Drive focus city. Fastest-growing EV 2W market in North-India Tier-2.",
    intro: "As UP's largest city and a PM E-Drive focus market, Lucknow is the fastest-growing electric two-wheeler hub in North India's Tier-2 belt. ElectricPe brings every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app for the whole city.",
    nearbyCitySlugs: ["ev-charging-stations-noida","ev-charging-stations-ghaziabad","ev-charging-stations-delhi"],
  },
  {
    slug: "ev-charging-stations-jaipur",
    pageType: "city-hub", name: "Jaipur", state: "Rajasthan", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Jaipur — ElectricPe",
    metaTitle: "Jaipur EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Jaipur with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet to pay.",
    priority: "high",
    rationale: "Top Tier-2 EV-adoption city. Nearby Alwar already has a confirmed operational mobility centre.",
    intro: "Jaipur ranks among India's top Tier-2 cities for EV adoption, with charging already live on the nearby Delhi Road corridor. ElectricPe maps stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet. Skip the hassle of juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-alwar","ev-charging-stations-gurugram","ev-charging-stations-delhi"],
    storeCitySlug: "jaipur",
  },
  {
    slug: "ev-charging-stations-alwar",
    pageType: "city-hub", name: "Alwar", state: "Rajasthan", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging in Alwar, Rajasthan — ElectricPe",
    metaTitle: "Alwar EV Charging Stations | ElectricPe",
    metaDescription: "Find EV charging stations across Alwar in the ElectricPe app — live availability from 60+ networks, easy navigation and one unified wallet to pay.",
    priority: "medium",
    rationale: "Mobility centre already operational. Serves the Alwar + Delhi Road corridor.",
    intro: "Alwar serves the busy Delhi Road corridor with charging already on the ground for commuters and highway travellers. ElectricPe brings every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet. One app instead of many.",
    nearbyCitySlugs: ["ev-charging-stations-jaipur","ev-charging-stations-gurugram","ev-charging-stations-delhi"],
    storeCitySlug: "alwar",
  },
  {
    slug: "ev-charging-stations-meerut",
    pageType: "city-hub", name: "Meerut", state: "Uttar Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Meerut — ElectricPe",
    metaTitle: "Meerut EV Charging Stations | ElectricPe",
    metaDescription: "Charge your EV across Meerut with the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet to pay.",
    priority: "medium",
    rationale: "Adjacent to Ghaziabad on the Namo Bharat metro corridor. Rapid EV adoption in West UP.",
    intro: "Connected to Ghaziabad on the Namo Bharat metro corridor, Meerut is seeing rapid EV adoption across West UP. ElectricPe maps charging stations from every major network onto one screen, so you can see live availability, navigate turn-by-turn, and pay from a single wallet — no juggling separate operator apps.",
    nearbyCitySlugs: ["ev-charging-stations-ghaziabad","ev-charging-stations-noida","ev-charging-stations-delhi"],
    storeCitySlug: "meerut",
  },
  {
    slug: "ev-charging-stations-nashik",
    pageType: "city-hub", name: "Nashik", state: "Maharashtra", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Nashik — ElectricPe App",
    metaTitle: "EV Charging Stations in Nashik | ElectricPe",
    metaDescription: "Find EV charging stations across Nashik in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Maharashtra manufacturing and wine belt. EV adoption growing rapidly.",
    intro: "Nashik's manufacturing units and wine-country routes are seeing EVs roll out fast, and ElectricPe pulls every nearby charger onto one screen. Open the app to check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet — no juggling separate operator apps across the city.",
    nearbyCitySlugs: ["ev-charging-stations-mumbai","ev-charging-stations-pune","ev-charging-stations-nagpur"],
  },
  {
    slug: "ev-charging-stations-indore",
    pageType: "city-hub", name: "Indore", state: "Madhya Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Indore — ElectricPe",
    metaTitle: "EV Charging Stations in Indore | ElectricPe",
    metaDescription: "Find EV charging stations across Indore in the ElectricPe app — live availability from 60+ networks, navigation and one unified wallet for cleaner driving.",
    priority: "high",
    rationale: "India's cleanest city. High civic awareness drives EV-adoption intent. MP EV policy improving.",
    intro: "Indore's reputation as India's cleanest city carries straight into how its drivers think about going electric. ElectricPe maps charging stations from every major network onto one screen, so you can check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet — clean travel made simple.",
    nearbyCitySlugs: ["ev-charging-stations-nagpur","ev-charging-stations-ahmedabad"],
  },
  {
    slug: "ev-charging-stations-coimbatore",
    pageType: "city-hub", name: "Coimbatore", state: "Tamil Nadu", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Coimbatore — ElectricPe",
    metaTitle: "EV Charging Stations in Coimbatore | ElectricPe",
    metaDescription: "Find EV charging stations across Coimbatore in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "South India's fastest-growing Tier-2 EV city. Manufacturing + textile hub means fleet demand.",
    intro: "Coimbatore's manufacturing and textile industries are driving real fleet-EV demand across South India's fastest-growing Tier-2 market. ElectricPe brings chargers from 60+ networks onto one screen, so you can see live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-chennai","ev-charging-stations-kochi","ev-charging-stations-bengaluru"],
  },
  {
    slug: "ev-charging-stations-kochi",
    pageType: "city-hub", name: "Kochi", state: "Kerala", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Kochi — Find Stations with ElectricPe",
    metaTitle: "EV Charging Stations in Kochi | ElectricPe",
    metaDescription: "Find EV charging stations across Kochi in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Kerala has the highest EV awareness of any state. Strong government push. Tourism fleet opportunity.",
    intro: "Kerala leads the country on EV awareness, and Kochi's tourism fleets and daily commuters are charging up across the city. ElectricPe maps stations from every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet without switching apps.",
    nearbyCitySlugs: ["ev-charging-stations-thiruvananthapuram","ev-charging-stations-coimbatore"],
  },
  {
    slug: "ev-charging-stations-thiruvananthapuram",
    pageType: "city-hub", name: "Thiruvananthapuram", state: "Kerala", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Thiruvananthapuram — ElectricPe",
    metaTitle: "EV Charging Stations Thiruvananthapuram | ElectricPe",
    metaDescription: "Find EV charging stations across Thiruvananthapuram in the ElectricPe app — live availability from 60+ networks, navigation and one unified wallet.",
    priority: "medium",
    rationale: "Kerala state capital. Government-employee fleet electrification. Growing Ather + Ola adoption.",
    intro: "As Kerala's capital, Thiruvananthapuram is seeing government fleets electrify and scooter adoption climb fast. ElectricPe gathers chargers from 60+ networks onto one screen, so you can check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet across the city.",
    nearbyCitySlugs: ["ev-charging-stations-kochi","ev-charging-stations-coimbatore"],
  },
  {
    slug: "ev-charging-stations-visakhapatnam",
    pageType: "city-hub", name: "Visakhapatnam", state: "Andhra Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Visakhapatnam — ElectricPe App",
    metaTitle: "EV Charging Stations Visakhapatnam | ElectricPe",
    metaDescription: "Find EV charging stations across Visakhapatnam in the ElectricPe app — live availability from 60+ networks, navigation and one unified wallet.",
    priority: "high",
    rationale: "Strong AP government EV policy. Port + logistics means fleet-EV demand.",
    intro: "Visakhapatnam's busy port and logistics corridors, backed by a strong Andhra Pradesh EV policy, are pushing fleets toward electric. ElectricPe maps charging stations from every major network onto one screen — see live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-vijayawada","ev-charging-stations-hyderabad","ev-charging-stations-tirupati"],
  },
  {
    slug: "ev-charging-stations-vijayawada",
    pageType: "city-hub", name: "Vijayawada", state: "Andhra Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Vijayawada",
    metaTitle: "EV Charging Stations in Vijayawada | ElectricPe",
    metaDescription: "Find EV charging stations across Vijayawada in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "AP capital zone. Government-employee EV push. Growing middle-class 2W EV adoption.",
    intro: "In the heart of Andhra Pradesh's capital zone, Vijayawada is seeing a government EV push meet rising middle-class scooter adoption. ElectricPe brings chargers from 60+ networks onto one screen, so you can check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-visakhapatnam","ev-charging-stations-hyderabad","ev-charging-stations-tirupati"],
  },
  {
    slug: "ev-charging-stations-tirupati",
    pageType: "city-hub", name: "Tirupati", state: "Andhra Pradesh", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Tirupati — ElectricPe",
    metaTitle: "EV Charging Stations in Tirupati | ElectricPe",
    metaDescription: "Find EV charging stations across Tirupati in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Major pilgrimage city with high vehicle density. Temple-trust vehicles going electric.",
    intro: "Tirupati's constant pilgrim traffic keeps the roads dense, and temple-trust vehicles are steadily switching to electric. ElectricPe maps charging stations from every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet across the pilgrimage city.",
    nearbyCitySlugs: ["ev-charging-stations-vijayawada","ev-charging-stations-chennai","ev-charging-stations-hyderabad"],
  },
  {
    slug: "ev-charging-stations-mysuru",
    pageType: "city-hub", name: "Mysuru", state: "Karnataka", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Mysuru — ElectricPe",
    metaTitle: "EV Charging Stations in Mysuru | ElectricPe",
    metaDescription: "Find EV charging stations across Mysuru in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Heritage + tourism city with high civic awareness. Karnataka expansion from Bengaluru.",
    intro: "Mysuru pairs heritage tourism with the same high civic awareness that powers Karnataka's EV growth from neighbouring Bengaluru. ElectricPe maps chargers from 60+ networks onto one screen, so you can see live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-bengaluru","ev-charging-stations-tumakuru","ev-charging-stations-mangaluru"],
    storeCitySlug: "mysuru",
  },
  {
    slug: "ev-charging-stations-hubballi",
    pageType: "city-hub", name: "Hubballi", state: "Karnataka", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging Stations in Hubballi — ElectricPe",
    metaTitle: "EV Charging Stations in Hubballi | ElectricPe",
    metaDescription: "Find EV charging stations across Hubballi in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Karnataka expansion from Bengaluru. Tourism + software workers. Strong 2W EV base.",
    intro: "Hubballi's growing software workforce and steady tourism sit on a strong two-wheeler EV base as Karnataka's network expands beyond Bengaluru. ElectricPe brings chargers from 60+ networks onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-belagavi","ev-charging-stations-mangaluru","ev-charging-stations-bengaluru"],
    storeCitySlug: "hubballi",
  },
  {
    slug: "ev-charging-stations-tumakuru",
    pageType: "city-hub", name: "Tumakuru", state: "Karnataka", tier: "T2",
    evPenetration: "Yes", operational: "Yes",
    h1: "EV Charging in Tumakuru — ElectricPe",
    metaTitle: "EV Charging Stations in Tumakuru | ElectricPe",
    metaDescription: "Find EV charging stations across Tumakuru in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Karnataka Tier-2 coverage near Bengaluru. Growing 2W EV adoption.",
    intro: "Just up the highway from Bengaluru, Tumakuru is seeing two-wheeler EV adoption climb as Karnataka's Tier-2 coverage fills in. ElectricPe maps charging stations from every major network onto one screen, so you can check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-bengaluru","ev-charging-stations-mysuru","ev-charging-stations-shivamogga"],
    storeCitySlug: "tumakuru",
  },
  {
    slug: "ev-charging-stations-mangaluru",
    pageType: "city-hub", name: "Mangaluru", state: "Karnataka", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Mangaluru — ElectricPe App",
    metaTitle: "EV Charging Stations in Mangaluru | ElectricPe",
    metaDescription: "Find EV charging stations across Mangaluru in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Coastal Karnataka with growing EV adoption. Port + tourism fleet opportunity.",
    intro: "On Karnataka's coast, Mangaluru's port traffic and tourism fleets are warming to electric as adoption grows. ElectricPe gathers chargers from 60+ networks onto one screen — see live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet across the coastal city.",
    nearbyCitySlugs: ["ev-charging-stations-mysuru","ev-charging-stations-hubballi","ev-charging-stations-bengaluru"],
  },
  {
    slug: "ev-charging-stations-belagavi",
    pageType: "city-hub", name: "Belagavi", state: "Karnataka", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Belagavi — ElectricPe",
    metaTitle: "EV Charging Stations in Belagavi | ElectricPe",
    metaDescription: "Find EV charging stations across Belagavi in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Confirmed operational mobility centre. North Karnataka border city with a real user base.",
    intro: "Belagavi, a North Karnataka border city, already has a real, active EV user base on the ground. ElectricPe maps charging stations from every major network onto one screen, so you can check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet — no operator-app juggling.",
    nearbyCitySlugs: ["ev-charging-stations-hubballi","ev-charging-stations-bengaluru"],
    storeCitySlug: "belagavi",
  },
  {
    slug: "ev-charging-stations-shivamogga",
    pageType: "city-hub", name: "Shivamogga", state: "Karnataka", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Shivamogga — ElectricPe",
    metaTitle: "EV Charging Stations in Shivamogga | ElectricPe",
    metaDescription: "Find EV charging stations across Shivamogga in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Karnataka Tier-2 coverage. Gateway to Malnad tourism with EV-tourism-circuit potential.",
    intro: "As the gateway to the Malnad hills, Shivamogga is a natural anchor for EV-tourism circuits in Karnataka's expanding Tier-2 coverage. ElectricPe brings chargers from 60+ networks onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet on every trip.",
    nearbyCitySlugs: ["ev-charging-stations-tumakuru","ev-charging-stations-hubballi","ev-charging-stations-bengaluru"],
  },
  {
    slug: "ev-charging-stations-kolkata",
    pageType: "city-hub", name: "Kolkata", state: "West Bengal", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Kolkata — ElectricPe",
    metaTitle: "EV Charging Stations in Kolkata | ElectricPe",
    metaDescription: "Find EV charging stations across Kolkata in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "India's 3rd-largest metro. West Bengal e-rickshaw policy means a massive 3W opportunity, plus rising 2W EV.",
    intro: "India's third-largest metro runs on a huge fleet of e-rickshaws, with two-wheeler EVs now rising fast alongside them. ElectricPe maps charging stations from every major network onto one screen across Kolkata — see live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet.",
    nearbyCitySlugs: ["ev-charging-stations-bhubaneswar","ev-charging-stations-guwahati"],
  },
  {
    slug: "ev-charging-stations-bhubaneswar",
    pageType: "city-hub", name: "Bhubaneswar", state: "Odisha", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging in Bhubaneswar — ElectricPe App",
    metaTitle: "EV Charging Stations Bhubaneswar | ElectricPe",
    metaDescription: "Find EV charging stations across Bhubaneswar in the ElectricPe app — live availability from 60+ networks, navigation and one unified wallet.",
    priority: "medium",
    rationale: "Smart City mission. IT corridor. Odisha government EV incentives improving.",
    intro: "A Smart City with a growing IT corridor, Bhubaneswar is seeing EV uptake rise as Odisha's incentives improve. ElectricPe gathers chargers from 60+ networks onto one screen, so you can check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet across the city.",
    nearbyCitySlugs: ["ev-charging-stations-kolkata","ev-charging-stations-visakhapatnam"],
  },
  {
    slug: "ev-charging-stations-guwahati",
    pageType: "city-hub", name: "Guwahati", state: "Assam", tier: "T2",
    evPenetration: "Expanding", operational: "Expanding",
    h1: "EV Charging Stations in Guwahati — ElectricPe",
    metaTitle: "EV Charging Stations in Guwahati | ElectricPe",
    metaDescription: "Find EV charging stations across Guwahati in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Northeast India gateway. Active Assam EV policy. Rising Ola S1 adoption.",
    intro: "As the gateway to Northeast India, Guwahati is riding an active Assam EV policy and rising electric-scooter adoption. ElectricPe maps charging stations from every major network onto one screen — check live availability, filter by connector and speed, navigate turn-by-turn, and pay from a single wallet across the city.",
    nearbyCitySlugs: ["ev-charging-stations-kolkata"],
  },
  {
    slug: "ev-charging-bengaluru-ola-s1",
    pageType: "vehicle-city",
    name: "Bengaluru",
    state: "Karnataka",
    h1: "Ola S1 Charging Stations in Bengaluru — ElectricPe",
    metaTitle: "Ola S1 Charging in Bengaluru | ElectricPe",
    metaDescription: "Find Ola S1 charging stations across Bengaluru in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "critical",
    rationale: "Ola S1 is India's #1-selling EV with the highest search volume. Bengaluru is the top Ola S1 city.",
    intro: "Riding an Ola S1 across Bengaluru means hunting for the right charge point — and ElectricPe puts every compatible station from 60+ networks on one screen. Open the app to see live availability, filter for the slow and fast points your S1 supports, navigate turn-by-turn, and pay from a single wallet without juggling apps.",
    nearbyCitySlugs: ["ev-charging-stations-bengaluru", "ev-charging-bengaluru-ather-450x"],
    vehicle: { brand: "Ola", model: "Ola S1" },
  },
  {
    slug: "ev-charging-delhi-ola-s1",
    pageType: "vehicle-city",
    name: "Delhi",
    state: "Delhi / NCR",
    h1: "Ola S1 Charging Stations in Delhi — ElectricPe App",
    metaTitle: "Ola S1 Charging in Delhi | ElectricPe",
    metaDescription: "Locate Ola S1 charging stations across Delhi NCR in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "critical",
    rationale: "Delhi is the #2 Ola S1 city with high search intent.",
    intro: "Charging your Ola S1 across Delhi NCR shouldn't mean checking five apps to find a free point — ElectricPe maps every compatible station from 60+ networks onto one screen. See which chargers are live right now, filter by the connector and speed your S1 needs, navigate straight there, and pay from one unified wallet.",
    nearbyCitySlugs: ["ev-charging-stations-delhi", "ev-charging-delhi-hero-vida"],
    vehicle: { brand: "Ola", model: "Ola S1" },
  },
  {
    slug: "ev-charging-bengaluru-ather-450x",
    pageType: "vehicle-city",
    name: "Bengaluru",
    state: "Karnataka",
    h1: "Ather 450X Charging in Bengaluru — ElectricPe",
    metaTitle: "Ather 450X Charging in Bengaluru | ElectricPe",
    metaDescription: "Find Ather 450X charging stations across Bengaluru in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Ather is HQ'd in Bengaluru with the highest Ather 450X concentration.",
    intro: "Your Ather 450X is at home in Bengaluru — and ElectricPe makes topping up anywhere just as easy by mapping every compatible charge point from 60+ networks onto one screen. Check live availability, filter for the connector and speed your 450X takes, navigate turn-by-turn, and pay from a single wallet instead of switching between apps.",
    nearbyCitySlugs: ["ev-charging-stations-bengaluru", "ev-charging-bengaluru-ola-s1"],
    vehicle: { brand: "Ather", model: "Ather 450X" },
  },
  {
    slug: "ev-charging-hyderabad-ather-450x",
    pageType: "vehicle-city",
    name: "Hyderabad",
    state: "Telangana",
    h1: "Ather 450X Charging in Hyderabad — ElectricPe",
    metaTitle: "Ather 450X Charging in Hyderabad | ElectricPe",
    metaDescription: "Find Ather 450X charging stations across Hyderabad in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Ather has a strong Hyderabad owner base.",
    intro: "Ather 450X owners across Hyderabad can skip the guesswork — ElectricPe brings every compatible charging point from 60+ networks together on one screen. Open the app to see which stations are free right now, filter by the connector and speed your 450X supports, navigate turn-by-turn, and settle up from one unified wallet.",
    nearbyCitySlugs: ["ev-charging-stations-hyderabad"],
    vehicle: { brand: "Ather", model: "Ather 450X" },
  },
  {
    slug: "ev-charging-chennai-tvs-iqube",
    pageType: "vehicle-city",
    name: "Chennai",
    state: "Tamil Nadu",
    h1: "TVS iQube Charging Stations Chennai — ElectricPe",
    metaTitle: "TVS iQube Charging in Chennai | ElectricPe",
    metaDescription: "Find TVS iQube charging stations across Chennai in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "TVS is HQ'd in Chennai; the iQube is a top 2W EV in South India.",
    intro: "Running a TVS iQube around Chennai means you need a charge point that's free and close — ElectricPe maps every compatible station from 60+ networks onto one screen. See live availability, filter for the connector and speed your iQube uses, navigate straight there, and pay from a single wallet without app-juggling.",
    nearbyCitySlugs: ["ev-charging-stations-chennai", "ev-charging-stations-coimbatore"],
    vehicle: { brand: "TVS", model: "TVS iQube" },
  },
  {
    slug: "ev-charging-pune-bajaj-chetak",
    pageType: "vehicle-city",
    name: "Pune",
    state: "Maharashtra",
    h1: "Bajaj Chetak Charging in Pune — ElectricPe App",
    metaTitle: "Bajaj Chetak Charging in Pune | ElectricPe",
    metaDescription: "Find Bajaj Chetak charging stations across Pune in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "high",
    rationale: "Bajaj is HQ'd in Pune; Chetak owners are Pune's core EV segment.",
    intro: "Your Bajaj Chetak belongs on Pune's roads — and ElectricPe makes charging it effortless by gathering every compatible point from 60+ networks onto one screen. Open the app to find which stations are live right now, filter by the connector and speed your Chetak takes, navigate turn-by-turn, and pay from one unified wallet.",
    nearbyCitySlugs: ["ev-charging-stations-pune", "ev-charging-stations-mumbai"],
    vehicle: { brand: "Bajaj", model: "Bajaj Chetak" },
  },
  {
    slug: "ev-charging-delhi-hero-vida",
    pageType: "vehicle-city",
    name: "Delhi",
    state: "Delhi / NCR",
    h1: "Hero Vida Charging Stations Delhi — ElectricPe",
    metaTitle: "Hero Vida Charging in Delhi | ElectricPe",
    metaDescription: "Find Hero Vida charging stations across Delhi NCR in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one unified wallet.",
    priority: "medium",
    rationale: "Hero MotoCorp is HQ'd in Delhi; the Vida V1 is popular in North India.",
    intro: "Hero Vida riders across Delhi NCR can stop hopping between apps to find a charge — ElectricPe puts every compatible station from 60+ networks on one screen. Check live availability, filter for the connector and speed your Vida supports, navigate turn-by-turn, and pay from a single unified wallet.",
    nearbyCitySlugs: ["ev-charging-stations-delhi", "ev-charging-delhi-ola-s1"],
    vehicle: { brand: "Hero", model: "Hero Vida" },
  },
  {
    slug: "ev-charging-bengaluru-mysuru-highway",
    pageType: "highway",
    name: "Bengaluru–Mysuru Highway",
    h1: "EV Charging Stations Bengaluru to Mysuru Highway",
    metaTitle: "EV Charging Bengaluru to Mysuru | ElectricPe",
    metaDescription: "Plan EV charging stops along the Bengaluru–Mysuru highway in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one wallet.",
    priority: "high",
    rationale: "India's first EV-ready expressway and the highest-traffic South India EV corridor (tourism + daily commute).",
    intro: "Driving the Bengaluru–Mysuru expressway is easy when you know exactly where to plug in — ElectricPe maps every charging stop along the corridor from 60+ networks onto one screen. Plan your top-ups before you set off, see which stations are live, navigate turn-by-turn, and pay from a single wallet so range anxiety never slows the trip.",
    nearbyCitySlugs: ["ev-charging-stations-bengaluru", "ev-charging-stations-mysuru"],
    route: { from: "Bengaluru", to: "Mysuru", distanceKm: 150 },
  },
  {
    slug: "ev-charging-delhi-jaipur-highway",
    pageType: "highway",
    name: "Delhi–Jaipur Highway",
    h1: "EV Charging Stations Delhi to Jaipur Highway (NH-48)",
    metaTitle: "EV Charging Delhi to Jaipur NH-48 | ElectricPe",
    metaDescription: "Map EV charging stops along the Delhi–Jaipur NH-48 corridor in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one wallet.",
    priority: "high",
    rationale: "The most-searched intercity EV charging route in North India.",
    intro: "Heading from Delhi to Jaipur on NH-48? ElectricPe lets you scout every charging stop along the corridor from 60+ networks before you leave, so range anxiety stays off the itinerary. See which stations are live in real time, navigate turn-by-turn to your next top-up, and pay from one unified wallet the whole way.",
    nearbyCitySlugs: ["ev-charging-stations-delhi", "ev-charging-stations-jaipur"],
    route: { from: "Delhi", to: "Jaipur", distanceKm: 280 },
  },
  {
    slug: "ev-charging-mumbai-pune-expressway",
    pageType: "highway",
    name: "Mumbai–Pune Expressway",
    h1: "EV Charging Mumbai to Pune Expressway — ElectricPe",
    metaTitle: "EV Charging Mumbai to Pune | ElectricPe",
    metaDescription: "Plan EV charging stops along the Mumbai–Pune Expressway in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one wallet.",
    priority: "high",
    rationale: "The busiest expressway in India with high 4W EV traffic.",
    intro: "The Mumbai–Pune Expressway is a quick run when your charging is mapped out — ElectricPe gathers every stop along the route from 60+ networks onto one screen. Plan a top-up before you climb the ghats, check live availability, navigate turn-by-turn, and pay from a single wallet instead of switching between network apps.",
    nearbyCitySlugs: ["ev-charging-stations-mumbai", "ev-charging-stations-pune"],
    route: { from: "Mumbai", to: "Pune", distanceKm: 95 },
  },
  {
    slug: "ev-charging-bengaluru-chennai-highway",
    pageType: "highway",
    name: "Bengaluru–Chennai Highway",
    h1: "EV Charging Bengaluru to Chennai — ElectricPe",
    metaTitle: "EV Charging Bengaluru to Chennai | ElectricPe",
    metaDescription: "Map EV charging stops on the Bengaluru–Chennai highway in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one wallet.",
    priority: "medium",
    rationale: "A South India EV corridor with high search demand from riders planning intercity trips.",
    intro: "Planning the Bengaluru–Chennai drive in an EV? ElectricPe shows every charging stop along the corridor from 60+ networks on one screen, so you can space your top-ups and beat range anxiety. Check which stations are live before you go, navigate turn-by-turn to each one, and pay from a single unified wallet end to end.",
    nearbyCitySlugs: ["ev-charging-stations-bengaluru", "ev-charging-stations-chennai"],
    route: { from: "Bengaluru", to: "Chennai", distanceKm: 346 },
  },
  {
    slug: "ev-charging-hyderabad-bengaluru-highway",
    pageType: "highway",
    name: "Hyderabad–Bengaluru Highway",
    h1: "EV Charging Hyderabad to Bengaluru Highway — ElectricPe",
    metaTitle: "EV Charging Hyderabad to Bengaluru | ElectricPe",
    metaDescription: "Plan EV charging stops on the Hyderabad–Bengaluru highway in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one wallet.",
    priority: "medium",
    rationale: "An EV charging gap exists on this corridor — an uncrowded query ElectricPe can own.",
    intro: "The long Hyderabad–Bengaluru haul demands careful charge planning — ElectricPe maps every available stop along the corridor from 60+ networks onto one screen so you're never stranded between cities. Line up your top-ups in advance, see live availability, navigate turn-by-turn, and pay from one unified wallet the whole way down.",
    nearbyCitySlugs: ["ev-charging-stations-hyderabad", "ev-charging-stations-bengaluru"],
    route: { from: "Hyderabad", to: "Bengaluru", distanceKm: 575 },
  },
  {
    slug: "ev-charging-delhi-agra-highway",
    pageType: "highway",
    name: "Delhi–Agra Yamuna Expressway",
    h1: "EV Charging Delhi to Agra — Yamuna Expressway",
    metaTitle: "EV Charging Delhi to Agra | ElectricPe",
    metaDescription: "Map EV charging stops on the Delhi–Agra Yamuna Expressway in the ElectricPe app — live availability from 60+ networks, turn-by-turn navigation and one wallet.",
    priority: "medium",
    rationale: "High-traffic tourist route with growing 4W EV travel demand; intercepts range-anxiety searches.",
    intro: "Touring from Delhi to Agra on the Yamuna Expressway is stress-free once your charging is sorted — ElectricPe puts every stop along the route from 60+ networks on one screen. Plan a top-up before you set out, check live availability, navigate turn-by-turn to the next charger, and pay from a single wallet so range worries never reach the Taj.",
    nearbyCitySlugs: ["ev-charging-stations-delhi"],
    route: { from: "Delhi", to: "Agra", distanceKm: 233 },
  },
  {
    slug: "home-ev-charger-installation-india",
    pageType: "use-case",
    name: "Home EV Charger Installation",
    h1: "Home EV Charger Installation India — ElectricPe Guide",
    metaTitle: "Home EV Charger Installation India | ElectricPe",
    metaDescription: "Get a home EV charger supplied and installed with ElectricPe — pick the right charger for your vehicle, charge overnight at home and manage it all in one app.",
    priority: "critical",
    rationale: "Highest top-of-funnel search volume in EV ownership; every new EV buyer searches this. ElectricPe sells home chargers.",
    intro: "Charging at home overnight is the easiest, lowest-cost way to run an EV — and ElectricPe supplies and installs the right home charger for your car or scooter. Tell us your vehicle and parking setup, get the matched charger fitted, and top up while you sleep, then use the same app to find public chargers from 60+ networks when you're out.",
  },
  {
    slug: "ev-fleet-charging-india",
    pageType: "use-case",
    name: "EV Fleet Charging",
    h1: "EV Fleet Charging Solutions India — ElectricPe",
    metaTitle: "EV Fleet Charging Solutions India | ElectricPe",
    metaDescription: "Power delivery, logistics and food-tech fleets with ElectricPe — access 25,000+ chargers across 60+ networks, one wallet and consolidated charging billing.",
    priority: "high",
    rationale: "B2B fleet segment: delivery, logistics, food-tech. High LTV, under-served by competitors.",
    intro: "Keeping a delivery, logistics or food-tech fleet on the road means charging that's reliable and easy to manage — ElectricPe gives your riders access to 25,000+ chargers across 60+ networks from one app. Drivers see live availability and navigate to the nearest free point, while you keep every charge on one unified wallet with consolidated billing instead of scattered receipts.",
  },
  {
    slug: "ev-charging-subscription-plan-india",
    pageType: "use-case",
    name: "EV Charging Subscription",
    h1: "Cheapest EV Charging Subscription Plan India — ElectricPe",
    metaTitle: "Cheapest EV Charging Subscription | ElectricPe",
    metaDescription: "Save on every charge with ElectricPe's low-cost charging subscription — a low per-unit plan across 25,000+ chargers and 60+ networks, all in one app.",
    priority: "critical",
    rationale: "ElectricPe's key differentiator is a low per-unit charging plan; core bottom-of-funnel content for cost-conscious buyers.",
    intro: "If you charge in public often, ElectricPe's low-cost charging subscription is the simplest way to save on every unit — a low per-unit plan that works across 25,000+ chargers from 60+ networks. Subscribe once, then see live availability, navigate turn-by-turn, and pay from a single wallet at your discounted rate wherever you plug in.",
  },
  {
    slug: "corporate-ev-charging-india",
    pageType: "use-case",
    name: "Corporate EV Charging",
    h1: "Corporate EV Charging Solutions India — ElectricPe",
    metaTitle: "Corporate EV Charging Solutions | ElectricPe",
    metaDescription: "Set up workplace EV charging with ElectricPe — install chargers at your office, give employees access to 60+ networks and manage usage and billing in one app.",
    priority: "high",
    rationale: "Target HR/Admin managers setting up corporate EV charging. High B2B LTV.",
    intro: "Offering EV charging at the office is a perk employees notice — and ElectricPe makes it simple for HR and admin teams to set up. Install workplace chargers, give your staff app access to 25,000+ public points across 60+ networks for trips beyond the office, and keep usage and billing consolidated on one dashboard and wallet.",
  },
  {
    slug: "ev-charging-for-apartments-india",
    pageType: "use-case",
    name: "EV Charging for Apartments",
    h1: "EV Charging for Apartments and Housing Societies India",
    metaTitle: "EV Charging for Apartments India | ElectricPe",
    metaDescription: "Bring EV charging to your apartment or housing society with ElectricPe — install shared chargers, manage resident access and billing, all from one app.",
    priority: "high",
    rationale: "Massive unmet need; every new apartment buyer with an EV searches this. Residential CPO upsell.",
    intro: "Owning an EV in an apartment shouldn't mean fighting over a single socket — ElectricPe helps your housing society install shared chargers residents can actually rely on. We handle the setup, give every resident app-based access and fair billing, and the same app maps 25,000+ public chargers from 60+ networks for when you're away from home.",
  },
];

const bySlug = new Map(chargingPages.map((p) => [p.slug, p]));

export const chargingPageSlugs: string[] = chargingPages.map((p) => p.slug);

export const getChargingPage = (slug: string): ChargingPage | undefined =>
  bySlug.get(slug);

export const getChargingPagesByType = (
  type: ChargingPageType,
): ChargingPage[] => chargingPages.filter((p) => p.pageType === type);

export const getNearbyChargingPages = (slug: string): ChargingPage[] => {
  const page = bySlug.get(slug);
  if (!page?.nearbyCitySlugs) return [];
  return page.nearbyCitySlugs
    .map((s) => bySlug.get(s))
    .filter((p): p is ChargingPage => Boolean(p));
};
