import type { Store } from "../types";

const standardHours = {
  mon: { open: "10:00", close: "20:00" },
  tue: { open: "10:00", close: "20:00" },
  wed: { open: "10:00", close: "20:00" },
  thu: { open: "10:00", close: "20:00" },
  fri: { open: "10:00", close: "20:00" },
  sat: { open: "10:00", close: "21:00" },
  sun: { open: "10:00", close: "18:00" },
} as const;

/**
 * Source of truth for store records is the official ElectricPe Store
 * Locations roster. Lat/lng values are corrected to true geo-centers where
 * the source spreadsheet contained obvious data-entry errors (several
 * Karnataka stores had coordinates pointing to Uttarakhand).
 */
export const stores: Store[] = [
  {
    slug: "agra-shyam-nagar",
    name: "ElectricPe EV Showroom Agra",
    cityId: "agra",
    state: "Uttar Pradesh",
    address:
      "1, Shyam Nagar, Shahganj Bodla Road, near Bank of India, Maruti Residency, Agra",
    pincode: "282010",
    lat: 27.1844,
    lng: 77.9687,
    phone: "+918951817700",
    whatsapp: "917906778737",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/agra-shyam-nagar.jpg"],
    managerName: "Ankit Sharma",
    storeCode: "AGR-SHN",
  },
  {
    slug: "aligarh-naveen-nagar",
    name: "ElectricPe EV Showroom Aligarh",
    cityId: "aligarh",
    state: "Uttar Pradesh",
    address:
      "1, Khair Bypass, near Chuab Singh School, Naveen Nagar, Aligarh",
    pincode: "202001",
    lat: 27.9011,
    lng: 78.0433,
    phone: "+918951817700",
    whatsapp: "918471033398",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/aligarh-naveen-nagar.webp"],
    managerName: "Ashish Kumar",
    storeCode: "ALG-NVN",
  },
  {
    slug: "alwar-jyoti-nagar",
    name: "ElectricPe EV Showroom Alwar",
    cityId: "alwar",
    state: "Rajasthan",
    address:
      "Shop No. 33, ND Sadan, Jyoti Nagar, Delhi Road, Mungaskha, near Hanuman Circle, Alwar",
    pincode: "301001",
    lat: 27.5560,
    lng: 76.6389,
    phone: "+918951817700",
    whatsapp: "918209602911",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/alwar-jyoti-nagar.jpg"],
    managerName: "Siddharth Singh",
    storeCode: "ALW-JTN",
  },
  {
    slug: "belagavi-shivaji-nagar",
    name: "ElectricPe EV Showroom Belagavi",
    cityId: "belagavi",
    state: "Karnataka",
    address:
      "Ground 4803/209, Shivaji Nagar 4th Line, Bharathi Shigihalli, Belagavi",
    pincode: "590016",
    lat: 15.8497,
    lng: 74.4977,
    phone: "+918951817700",
    whatsapp: "919535499019",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/belagavi-shivaji-nagar.jpg"],
    managerName: "Basavraj",
    storeCode: "BGM-SHV",
  },
  {
    slug: "bengaluru-kalyan-nagar",
    name: "ElectricPe EV Showroom Kalyan Nagar",
    cityId: "bengaluru",
    state: "Karnataka",
    address:
      "100 feet Ring Road, Annaiya Reddy Layout, Dodda Banaswadi Main Rd, opp. Global Boutique, Bengaluru",
    pincode: "560043",
    lat: 13.0283,
    lng: 77.6408,
    phone: "+918951817700",
    whatsapp: "917892104511",
    hours: standardHours,
    services: ["sales", "service", "testRides", "charging"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/bengaluru-kalyan-nagar.jpg"],
    managerName: "Niyamath Ulla",
    storeCode: "BLR-KLN",
  },
  {
    slug: "davanagere-vidyanagar",
    name: "ElectricPe EV Showroom Davanagere",
    cityId: "davanagere",
    state: "Karnataka",
    address:
      "Kalleshwara Complex, 1341, Taralabalu Layout, Vidyanagar, Davanagere",
    pincode: "577005",
    lat: 14.4644,
    lng: 75.9218,
    phone: "+918951817700",
    whatsapp: "919019664387",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/davanagere-vidyanagar.jpg"],
    managerName: "Tanu",
    storeCode: "DVG-VDN",
  },
  {
    slug: "delhi-budh-vihar",
    name: "ElectricPe EV Showroom Budh Vihar",
    cityId: "delhi",
    state: "Delhi",
    address:
      "Landmark Palaz Pur Modr, State Bank of Patiala, Village Pooth Kalan, District Mangol Puri, New Delhi",
    pincode: "110086",
    lat: 28.7144,
    lng: 77.0764,
    phone: "+918951817700",
    whatsapp: "918383921219",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/delhi-budh-vihar.jpeg"],
    managerName: "Sagar",
    storeCode: "DEL-BDV",
  },
  {
    slug: "delhi-dwarka",
    name: "ElectricPe EV Showroom Dwarka",
    cityId: "delhi",
    state: "Delhi",
    address:
      "Plot No-12-A, Ground Flat No-264B, Khasra No-99/18, Vishwash Park, Uttam Nagar, Dwarka, New Delhi",
    pincode: "110059",
    lat: 28.6058,
    lng: 77.0537,
    phone: "+918951817700",
    whatsapp: "918866488264",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/delhi-dwarka.jpg"],
    managerName: "Ketan Bansal",
    storeCode: "DEL-DWR",
  },
  {
    slug: "delhi-jahangirpuri",
    name: "ElectricPe EV Showroom Jahangirpuri",
    cityId: "delhi",
    state: "Delhi",
    address:
      "House No. 75, Block C, Village Ram Garh, near Jahangirpuri Metro Station, New Delhi",
    pincode: "110033",
    lat: 28.7407,
    lng: 77.1631,
    phone: "+918951817700",
    whatsapp: "917065968597",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/delhi-jahangirpuri.jpeg"],
    managerName: "Mansoob Alam",
    storeCode: "DEL-JHP",
  },
  {
    slug: "delhi-krishna-nagar",
    name: "ElectricPe EV Showroom Krishna Nagar",
    cityId: "delhi",
    state: "Delhi",
    address:
      "Plot 33, Gali No. 3, Arjun Nagar, near Krishna Nagar Metro Station, East Delhi",
    pincode: "110051",
    lat: 28.6576,
    lng: 77.2902,
    phone: "+918951817700",
    whatsapp: "919540509292",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/delhi-krishna-nagar.webp"],
    managerName: "Rahul Kumar",
    storeCode: "DEL-KRN",
  },
  {
    slug: "delhi-nawada",
    name: "ElectricPe EV Showroom Nawada",
    cityId: "delhi",
    state: "Delhi",
    address:
      "Plot No-4, Nawada Extn, beside Khasra 783, Uttam Nagar, New Delhi",
    pincode: "110059",
    lat: 28.6207,
    lng: 77.0484,
    phone: "+918951817700",
    whatsapp: "919220759394",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/delhi-nawada.jpg"],
    managerName: "Diwakar",
    storeCode: "DEL-NWD",
  },
  {
    slug: "dharwad-line-bazar",
    name: "ElectricPe EV Showroom Dharwad",
    cityId: "dharwad",
    state: "Karnataka",
    address:
      "Sy No 218/1A/B, Line Bazar, opp. Laxmi Talkies, near Paral Bar, Dharwad",
    pincode: "580001",
    lat: 15.4589,
    lng: 75.0078,
    phone: "+918951817700",
    whatsapp: "919731163205",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/dharwad-line-bazar.webp"],
    managerName: "Ramesh Badiger",
    storeCode: "DWR-LBZ",
  },
  {
    slug: "ghaziabad-meerut-road",
    name: "ElectricPe EV Showroom Meerut Road",
    cityId: "ghaziabad",
    state: "Uttar Pradesh",
    address:
      "Pillar no. 570 of Namo Bharat Metro, near Chetak Electric Experience Showroom, Baba Nagar, Meerut Road, Ghaziabad",
    pincode: "201003",
    lat: 28.6875,
    lng: 77.4327,
    phone: "+918951817700",
    whatsapp: "919540824240",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/ghaziabad-meerut-road.jpg"],
    managerName: "Anurag Mishra",
    storeCode: "GZB-MRT",
  },
  {
    slug: "ghaziabad-tigri-circle",
    name: "ElectricPe EV Showroom Tigri Circle",
    cityId: "ghaziabad",
    state: "Uttar Pradesh",
    address:
      "Lower Ground - 1, New Complex near Triveni Almirah Showroom, Tigri Gol Chakkar, Taj Highway, Ghaziabad",
    pincode: "201001",
    lat: 28.6298,
    lng: 77.4127,
    phone: "+918951817700",
    whatsapp: "918950073003",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/ghaziabad-tigri-circle.jpg"],
    managerName: "Pradeep",
    storeCode: "GZB-TGC",
  },
  {
    slug: "gurugram-mata-road",
    name: "ElectricPe EV Showroom Gurugram",
    cityId: "gurugram",
    state: "Haryana",
    address:
      "871/2, Mata Road, Ganga Vihar, near Mamta Hospital, Gurugram",
    pincode: "122006",
    lat: 28.4688,
    lng: 77.0337,
    phone: "+918951817700",
    whatsapp: "918791373541",
    hours: standardHours,
    services: ["sales", "service", "testRides", "charging"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/gurugram-mata-road.jpeg"],
    managerName: "Anuradha",
    storeCode: "GGM-MTR",
  },
  {
    slug: "hassan-bm-road",
    name: "ElectricPe EV Showroom Hassan",
    cityId: "hassan",
    state: "Karnataka",
    address:
      "Ground Floor 1, 2 & 3, Sri Shivalingeshwara Complex, 5th Cross, Thaneerhulla Mutta, B M Road, Siddaiah Nagar, Hassan",
    pincode: "573201",
    lat: 13.0072,
    lng: 76.0962,
    phone: "+918951817700",
    whatsapp: "918892055024",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/hassan-bm-road.jpg"],
    managerName: "Praveen Kumar",
    storeCode: "HSN-BMR",
  },
  {
    slug: "hubballi-vidya-nagar",
    name: "ElectricPe EV Showroom Hubballi",
    cityId: "hubballi",
    state: "Karnataka",
    address:
      "Ground, Canara Hotel, Ronad Building, 23A/6/D, Pune-Bangalore Road, Vidya Nagar, Hubballi",
    pincode: "580021",
    lat: 15.3647,
    lng: 75.1240,
    phone: "+918951817700",
    whatsapp: "918553283196",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/hubballi-vidya-nagar.jpg"],
    managerName: "Abdul Raheem",
    storeCode: "HUB-VDN",
  },
  {
    slug: "jaipur-sanganer",
    name: "ElectricPe EV Showroom Jaipur",
    cityId: "jaipur",
    state: "Rajasthan",
    address: "A2, Dev Nikunj, Khokhawas, Tonk Road, Sanganer, Jaipur",
    pincode: "302029",
    lat: 26.8223,
    lng: 75.7951,
    phone: "+918951817700",
    whatsapp: "918003483521",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/jaipur-sanganer.jpg"],
    managerName: "Dharmendra Singh",
    storeCode: "JAI-SGR",
  },
  {
    slug: "mandya-bannur-road",
    name: "ElectricPe EV Showroom Mandya",
    cityId: "mandya",
    state: "Karnataka",
    address: "1689-1690, Bannur-Mandya Rd, Vidya Nagar, Mandya",
    pincode: "571401",
    lat: 12.5246,
    lng: 76.8966,
    phone: "+918951817700",
    whatsapp: "918553385344",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/mandya-bannur-road.jpg"],
    managerName: "Sharukh",
    storeCode: "MDY-BNR",
  },
  {
    slug: "mathura-goverdhan-chauraha",
    name: "ElectricPe EV Showroom Mathura",
    cityId: "mathura",
    state: "Uttar Pradesh",
    address:
      "Goverdhan Chauraha, in front of KM Residency, Mathura",
    pincode: "281004",
    lat: 27.5001,
    lng: 77.6522,
    phone: "+918951817700",
    whatsapp: "918057513549",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/mathura-goverdhan-chauraha.jpg"],
    managerName: "Vivek Sharma",
    storeCode: "MTR-GVD",
  },
  {
    slug: "meerut-garh-road",
    name: "ElectricPe EV Showroom Garh Road",
    cityId: "meerut",
    state: "Uttar Pradesh",
    address:
      "5-A, Garh Road, near Nandan Cinema, Kailash Puri, Meerut",
    pincode: "250002",
    lat: 28.9724,
    lng: 77.7157,
    phone: "+918951817700",
    whatsapp: "918307486695",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/meerut-garh-road.jpg"],
    managerName: "Rohit Kumar",
    storeCode: "MRT-GRD",
  },
  {
    slug: "meerut-roorkee-road",
    name: "ElectricPe EV Showroom Roorkee Road",
    cityId: "meerut",
    state: "Uttar Pradesh",
    address:
      "5B-6B, Parivahan Puram, Roorkee Road, Kuber School, Dorli Naka, Meerut",
    pincode: "250001",
    lat: 29.0442,
    lng: 77.7074,
    phone: "+918951817700",
    whatsapp: "917060059058",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/meerut-roorkee-road.jpg"],
    managerName: "Amit Sharma",
    storeCode: "MRT-RKR",
  },
  {
    slug: "mysuru-kg-koppal",
    name: "ElectricPe EV Showroom Mysuru",
    cityId: "mysuru",
    state: "Karnataka",
    address:
      "2763, Railway Gate Rd, K.G Koppal, Kannegowdana Koppalu, Mysuru",
    pincode: "570009",
    lat: 12.2958,
    lng: 76.6394,
    phone: "+918951817700",
    whatsapp: "917406919770",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/mysuru-kg-koppal.png"],
    managerName: "Sanjeev Kumar",
    storeCode: "MYS-KGK",
  },
  {
    slug: "rohtak-chhotu-ram-nagar",
    name: "ElectricPe EV Showroom Rohtak",
    cityId: "rohtak",
    state: "Haryana",
    address:
      "532, Chhotu Ram Nagar, near Sukhpura, on Outer City Road, Rohtak",
    pincode: "124001",
    lat: 28.9112,
    lng: 76.5882,
    phone: "+918951817700",
    whatsapp: "919992044546",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/rohtak-chhotu-ram-nagar.webp"],
    managerName: "Chirag Kathuria",
    storeCode: "RHK-CRN",
  },
  {
    slug: "sonipat-sector-13",
    name: "ElectricPe EV Showroom Sonipat",
    cityId: "sonipat",
    state: "Haryana",
    address:
      "Ground Floor, 424, Raj Tower, Sector-13, Delhi Road, Sonipat",
    pincode: "131001",
    lat: 28.9903,
    lng: 77.0349,
    phone: "+918951817700",
    whatsapp: "917206851661",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/sonipat-sector-13.jpg"],
    managerName: "Yogesh",
    storeCode: "SNP-S13",
  },
  {
    slug: "tumakuru-main-road",
    name: "ElectricPe EV Showroom Tumakuru",
    cityId: "tumakuru",
    state: "Karnataka",
    address:
      "Ground Floor 9, Adishakti Complex, Tumkur Main Road, opp. SBI Bank Tumkur, Ramajoyish Nagar, Tumakuru",
    pincode: "572105",
    lat: 13.3392,
    lng: 77.1140,
    phone: "+918951817700",
    whatsapp: "919980487857",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/stores/tumakuru-main-road.webp"],
    managerName: "Bhanuprakash",
    storeCode: "TMK-MNR",
  },
];

export const getStoresByCity = (citySlug: string): Store[] =>
  stores.filter((s) => s.cityId === citySlug);

export const getStore = (slug: string): Store | undefined =>
  stores.find((s) => s.slug === slug);
